### ISSUE TITLE
June 10 Deployment: Validation not generating expected results

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#1004]
CS: 
If ORDER.OBSERVATION.OBX-3.1 (Identifier) contain the value '12345'. then ( ( ORDER.OBSERVATION.OBX-2 (Value Type) shall contain the value 'ST'. AND All occurrences of ORDER.OBSERVATION.OBX-5 (Observation Value) shall contain the value 'F'. ) OR ( ORDER.OBSERVATION.OBX-2 (Value Type) shall contain the value 'CWE'. AND All occurrences of ORDER.OBSERVATION.OBX-5 (Observation Value) shall not contain one of the values in the list: ['A','B']. ) )
--
The XML:
![image](https://user-images.githubusercontent.com/14842422/84524859-9d31ef00-aca8-11ea-9bcb-78a8a0cab866.png)

I don't think I tested this before.

**Comment by HossamT** [comment]
What does the validation generate? 
Can you provide a bunldle

**Comment by smartinez290** [comment]
@HossamT Let's see if I can find the original IG....

**Comment by smartinez290** [comment]
[NIST-IGAMT-Profiling-Guide-[DRAFT]-5e833bd0b3cb1f000643a624_20200805_165511.zip](https://github.com/usnistgov/hl7-igamt/files/5029931/NIST-IGAMT-Profiling-Guide-.DRAFT.-5e833bd0b3cb1f000643a624_20200805_165511.zip)
