### ISSUE TITLE
June 10 Deployment: Validation on HL70396 dyn table

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#1006]
@Jungyubw 
Why is the validator generating the last two errors in this image? I know you are working on it. I will like to tack it. 
![image](https://user-images.githubusercontent.com/14842422/84534736-7a0f3b80-acb8-11ea-991b-823337e54766.png)

**Comment by Jungyubw** [comment]
@Abdelghani90 as you requested, I have fixed binding Indentifier of HL70396 for XML exporting. made PullRequest

**Comment by Abdelghani90** [comment]
@smartinez290 do you still have this issue ?
