### ISSUE TITLE
June 10 Deployment - Co-Constraint Table Export

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#1010]
OBX-6: is a constant value, there is no code system, therefore the code system label is not necessary.

There is not a co-constraint condition, therefore the co-constraint condition label is not necessary.

![image](https://user-images.githubusercontent.com/14842422/84698056-2cdfd380-af1d-11ea-98d3-513d64baf226.png)
Why is the If column highlighted in blue?

**Comment by smartinez290** [comment]
@YoussefBouij the Co-constraint Condition is still showing in the export with no value. Let me know if this is the acceptable behaviour to close the ticket. The other issue is fixed.

![image](https://user-images.githubusercontent.com/14842422/89448804-1f2d1a00-d726-11ea-99ce-5aac26a98f9f.png)

**Comment by YoussefBouij** [comment]
Yeah I noticed this one while working on the other issue you reported earlier. I'll fix this one with the rest.
