### ISSUE TITLE
June 10 Deployment - Conditional Co-Constraint UI

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#1011]
The UI is not consistent.
Selected Simple Assertion Type 
the following screen pop up:

![image](https://user-images.githubusercontent.com/14842422/84701961-e3df4d80-af23-11ea-9cdf-4f317224be4b.png)

Select the Target Node and the previous screen is gone and replaced by this one:
![image](https://user-images.githubusercontent.com/14842422/84702080-15581900-af24-11ea-8de7-63d35275e4ab.png)

only "is valued" and "is not valued" declarative statements are available, I am not able to select any other decalration.

**Comment by smartinez290** [comment]
@HossamT was this issue addressed in the last deployment?

**Comment by HossamT** [comment]
Yes, should be fixed

**Comment by smartinez290** [comment]
Just QAed is working!! Thanks.
