### ISSUE TITLE
June 10 Deployment: User's Guide TOC Sections

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#1015]
@Abdelghani90 is it possible to make the sections in the User's Guide more legible. More like the old IGAMT.

![image](https://user-images.githubusercontent.com/14842422/84927218-83265100-b09a-11ea-8520-686a77411079.png)

The sections in IGAMAT-2 are too constricted.

![image](https://user-images.githubusercontent.com/14842422/84927404-cc76a080-b09a-11ea-8d10-fb8e908dddd1.png)

**Comment by Abdelghani90** [comment]
I ll certainly do. Thanks for reporting
