### ISSUE TITLE
June 10 Deployment: Editor Options

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#1017]
@Abdelghani90 
Per Chrisy (CDC): The Editor Options tend to disappear while adding narrative. I had the same experience. If I add a lot of info, the edit ribbon can't be found. I usually have to save the changes and get back in.

**Comment by Abdelghani90** [comment]
Could you provide a picture if it happens again?

**Comment by smartinez290** [comment]
@Abdelghani90 closing this one, we provided her with the option of expanding and now she can see the ribbon
