### ISSUE TITLE
Opening IG -- pop up

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#1026]
The following screen keep showing up after opening an IG

![image](https://user-images.githubusercontent.com/14842422/85410160-bce0d700-b534-11ea-877c-d74889c701c8.png)

**Comment by smartinez290** [comment]
@Abdelghani90 I have to click Export in order to get back to the IG. I can't cancel out

**Comment by Abdelghani90** [comment]
Thanks for reporting. we will fix ASAP
