### ISSUE TITLE
Derived IG - Value set delta 

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#1037]
I removed a code from a value set in a derived IG. I added the code back, but differential view indicates that there is an update on that value set.  I click on delta and I do not see any update.

**Comment by Abdelghani90** [comment]
We don't support that for now. It would be hard to implement if we decide to do so.

**Comment by smartinez290** [comment]
![image](https://user-images.githubusercontent.com/14842422/87345198-be8f3080-c51d-11ea-820c-8bac49ba1d2a.png)
