### ISSUE TITLE
July 22 Deployment: Derived IG Export  HTML Fatal error

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#1054]

**Comment by smartinez290** [comment]
Derived IG | Differential View On | Default Config  | HTML Quick  ==> Fatal error

**Comment by Abdelghani90** [comment]
Hi Sandra please provide the url of the IG

**Comment by smartinez290** [comment]
@Abdelghani90 issue is still active,  Youssef and Ismail identified the problem, they are working on it.
