### ISSUE TITLE
Unable to edit PHINVADS created as flavor with codes

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#1080]
Created a PHINVADS value set as flavor with codes.

I am able to edit under Value set definition, but I can't edit in meta data, pre-definition and post-definition.

**Comment by Abdelghani90** [comment]
@smartinez290 Any updates on this one?

**Comment by smartinez290** [comment]
@mellouli-dev now I am able to edit meta data but I can't still enter pre-definition and post-definition. A I missing something? This is happening in all v/s not only PhinVads.
