### ISSUE TITLE
Unexpected export behaviour for Conformance Profile

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#1081]
Create and user export configuration choose not to export Optional Segments in Conformance Profiles. When exporting I can still see optional segments, but only in one Conformance Profile. The other Conf. profiles are working correctly not exporting optional segments even though they have optional segments in their definition just like the first one that still show optional segments in the export.  Please  @Abdelghani90  have a field day with this one. Youssef can explain further.

**Comment by smartinez290** [comment]
@Abdelghani90 @YoussefBouij was this issue addressed and ready for QA?

**Comment by YoussefBouij** [comment]
Not yet

**Comment by smartinez290** [comment]
Duplicate
