### ISSUE TITLE
Last User Configuration Export 

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#1084]
IGAMT is not exporting the last user configuration in this scenario:
1. Open IG and export (default config used) 
2. Exported again but now with a User defined config (Segment_include_Optional) 
3. Made an IG Mod (ACK profile segment R-RE) 
4. Based on my understanding, if I go to customized and click on Use Last User Config I should be getting the export with the last config (segment_include_optional)

**Comment by smartinez290** [comment]
@YoussefBouij was this issue addressed in the last deployment and ready for QA?

**Comment by YoussefBouij** [comment]
Not yet.
