### ISSUE TITLE
Value set/single code vs constant value

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1093]
Should value set/single code and constant value be allowed at the same time ?
![image](https://user-images.githubusercontent.com/13591511/90565243-99bd5700-e174-11ea-9912-3d34c413641c.png)

I discussed the options with Sandra and Rob and here are the different possibilities:

1.	Don’t do anything – if users want to hang themselves, it’s their problem. The issue here is that we’re allowing them to continue “bad practices”.
2.	Don’t allow value set/single code if there is a constant value, don’t allow constant value if there is a value set/single code (so basically it’s one or the other, not both at the same time)
3.	Only allow constant value for non-coded element (so that requires some logic to check if an element is a coded element, based on datatype). We would still have elements where value sets/single code AND constant value is allowed because we have a list of exception to allow value set.
4.	A mix of option 2 & 3.

We can discuss that during the next meeting.

**Comment by carolinerosin** [comment]
I'm pretty sure we went with option "don't do anything" at that time.

**Comment by Abdelghani90** [comment]
I would go for option-1. If you agree then we can close the ticket.
