### ISSUE TITLE
Co-constraint "delete segment" workflow issue ?

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1094]
1. add a co-constraint table binding
2.  select context
3.  select segment
4.  delete segment

At that point there is no way to add another segment to the context. User is forced to delete context and re-create it if he want to select another segment. Or maybe there is something I didn't see ?

![image](https://user-images.githubusercontent.com/13591511/90646351-1f88e300-e205-11ea-9bd3-48917a17098b.png)

**Comment by HossamT** [comment]
You can add it by clicking the [+ Add Co-Constraint Table Binding] button and select the same context and segment you want, I agree this is not clear and would be easier by adding a button at the context level. 
This UI has already a lot of buttons which makes it a little overwhelming to users, I was looking at minimizing the number of buttons if something could be done a different way.
