### ISSUE TITLE
Share Option not working as expected

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#1106]
The user, Chrissy from CDC, indicated that she shared the IG with another user "tried to make it read-only" but when she accessed the IG she was not able to edit anymore. 

@Abdelghani90 just capturing the issue and giving you and additional deatail.

**Comment by smartinez290** [comment]
@Jungyubw @robnist also, I think this share option workflow must be revised... it is confusing for the user.

**Comment by Jungyubw** [comment]
I will look at this. @smartinez290 Can I meet on BJ tomorrow?

Thanks.

**Comment by smartinez290** [comment]
@Jungyubw sure I will contact you with link on Slack

**Comment by Jungyubw** [comment]
fixed
