### ISSUE TITLE
Len and Conf. Len

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#1108]
Just to capture the issue per Hossam: "I just noticed that it might not be clear to the users that Length and Conformance Length are related and that you can only have one active at the time (and you activate the one by deactivating the other)
 
Also @Woo, Jung Yub (Assoc) in the XML serialization do you take into consideration the attribute lengthType? It should be used to either serialize Length or ConfLength.

**Comment by Jungyubw** [comment]
I have fixed for Length in XML.

If user selects ConfLength, then Min/MaxLength is NA and ConfLength will be used.
If user selects Length, then ConfLength is NA, and Min/MaxLength will be used.
