### ISSUE TITLE
September 15 Deployment - Deleting IG

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#1130]
I am the owner of the IG I  am trying to delete, but I am getting this message:

![image](https://user-images.githubusercontent.com/14842422/93339892-1ede6f00-f7fa-11ea-98af-e029e91e3830.png)

**Comment by Abdelghani90** [comment]
Hi Sandra, you should unshare it with all the other users then save then delete

**Comment by smartinez290** [comment]
Thank you for the clarification. It is working.... but the message is not clear. It does not say anything about IG been shared.

**Comment by Abdelghani90** [comment]
ok I will close now, We will review the share anyway..
