### ISSUE TITLE
September 16 Deployment QA: Unexpected validation error on 2.5.1 IG

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#1137]
The validator is generating an unexpected Constraint Failure on IZ-48 CS.
@woo if you need additional info let me know. 
![image](https://user-images.githubusercontent.com/14842422/93504887-1a907f80-f8e8-11ea-8627-487189db7632.png)

**Comment by smartinez290** [comment]
@Jungyubw I think this is also related. another expected error related to RXA-20 not populated and is "RE"
![image](https://user-images.githubusercontent.com/14842422/93506095-bd95c900-f8e9-11ea-8dbf-b221e13dd6ac.png)

**Comment by Jungyubw** [comment]
@smartinez290 
I cannot see your full message, but I guess RXA-20 is empty and RXA-6 is 0.5 (not 999).

IZ-48: If RXA-20 (Completion Status) contain the value 'RE'. then RXA-6 (Administered Amount) shall contain the value '999'.

This IZ-48 is 'if-then' constraint. And RXA-20 is empty, so your just plain-text condition is true. This is normal behavior.
If you want to exclude empty value, you need to add presence check for this. The tool does not create presence check automatically for PlainText. (This is same for old IGAMT. We added presence check for CoConstraint rules).
