### ISSUE TITLE
September 16 Deployment QA: Unexpected validation response

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#1138]
Why I am not getting an error on an optional element that was populated with the incorrect data? When I process the same message in the ONC IZ tool I get the error. 
I am expecting this error: Field ORC-9 (Date/Time of Transaction) has extra children
On this message: 
MSH|^~\&|||||20200909102500-0600||ACK^Q11^ACK|3ZNT-SA.8.1.1-D|P|2.5.1|||ER|AP|||||Z22^CDCPHINVS^Test^TEst||||Test^TEST
PID|1||J42J7772^^^AIRA^MR||ChampaignAIRA^CaelynAIRA^Violeta^^^^L|ParkAIRA^MaritzaAIRA^^^^^M|20160829|F||2106-3^White^CDCREC|1343 Rluis Ave^^Atlantic Mine^MI^49905^USA^P||^PRN^PH^^^906^5239440|||||||||2186-5^not Hispanic or Latino^CDCREC||N||||||N
PD1|||||||||||02^Reminder/Recall - any method^HL70215|N|20200909|||A|20200909|20200909
NK1|1|ChampaignAIRA^ParkAIRA^Marion^^^^L|MTH^Mother^HL70063|1343 Rluis Ave^^Atlantic Mine^MI^49905^USA^P|^PRN^PH^^^906^5239440
ORC|RE|AJ42J7772.1^AIRA|BJ42J7772.1^AIRA||||||1234^^^^^^^Test^Test2^Test3
RXA|100|2|20170909|20180809|94^MMRV^CVX|999|||01^Historical^NIP001|||||||||00||RE|A
OBX|1|CE|75505-8^Disease with serological evidence of immunity^LN|-1|271511000^Serology confirmed Hepatitis B^SCT||||||F|||20200909

XML:
[HL7-Version-2.5.1-Implementation-Guide-for-Immunization-Messaging_Sept16_Copy-5f620e7b9194be0006a435f5_20200917_180342.zip](https://github.com/usnistgov/hl7-igamt/files/5241062/HL7-Version-2.5.1-Implementation-Guide-for-Immunization-Messaging_Sept16_Copy-5f620e7b9194be0006a435f5_20200917_180342.zip)

**Comment by Jungyubw** [comment]
@smartinez290 


The message is weird.
Is this an ACK message? (It doesn't look like that..) Could you please provide a screenshot of the error?

**Comment by smartinez290** [comment]
@Jungyubw this is not an ACK message. The issue is that there is no error generated. It is an optional element. @HossamT indicated that error for optional elements must be included under alerts. But, no error is generated at all. 

When I look at the ONC2015 IZtool the validator generates an error on this this element (ORC-9):
![image](https://user-images.githubusercontent.com/14842422/93771523-9f7ee000-fbeb-11ea-9d10-d2a804ce0059.png)

**Comment by Jungyubw** [comment]
@smartinez290  I just want to know where you get this error in ONC 2015 tool. Could you provide full screen for this? Or just show it via bluejeans. 

Thanks.

**Comment by smartinez290** [comment]
@Jungyubw This is the screen shot for ONC2015 Iztool: The Extra error on ORC-9
![image](https://user-images.githubusercontent.com/14842422/93774146-ea4e2700-fbee-11ea-9ede-dd28698eb252.png)

**Comment by carolinerosin** [comment]
@smartinez290 did you check the default configuration ? For me the "extra" detection category is a warning by default
![image](https://user-images.githubusercontent.com/13591511/93925773-9cb3e600-fce4-11ea-8595-fa9b96939cf2.png)

**Comment by smartinez290** [comment]
@carolinerosin is showing up as warning... If that is correct, I will close this issue.
