### ISSUE TITLE
September 16 Deployment - Unexpected Validation Error

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#1139]
Pushing the 2.5.1 VXU profile to GVT

Why is this error generated?
![image](https://user-images.githubusercontent.com/14842422/93512498-62b49f80-f8f2-11ea-93aa-f6503a42dea6.png)

 I ran the same message thru the 2015 IZtool and no error is generated. RXA-9.1 is empty. What is the correct validation response in this situation?

Included is the XML.
[HL7-Version-2.5.1-Implementation-Guide-for-Immunization-Messaging_Sept16_Copy-5f620e7b9194be0006a435f5_20200917_180342.zip](https://github.com/usnistgov/hl7-igamt/files/5241174/HL7-Version-2.5.1-Implementation-Guide-for-Immunization-Messaging_Sept16_Copy-5f620e7b9194be0006a435f5_20200917_180342.zip)

**Comment by Jungyubw** [comment]
@smartinez290 

This is same situation for #1138 

This comes from 2015 IZ tool:
![image](https://user-images.githubusercontent.com/13385213/93649740-aa165b00-f9da-11ea-860d-b5c390250056.png)

This is yours:
![image](https://user-images.githubusercontent.com/13385213/93649690-93700400-f9da-11ea-9692-5534199717c2.png)

In the yours, there is missing presence check. Both old and new IGAMT does not create PlainText automatically.

**Comment by smartinez290** [comment]
@Jungyubw so what does this mean? Does the CS must be modified to add a presence check?

**Comment by Jungyubw** [comment]
Yes, If element usage is Optional and user wants to make it Plaintext, the presence check should be added. We did same things for old IGAMT. We can discuss this for tool to add automatically, but we need to think of unexpected side effects.
