### ISSUE TITLE
[BUG]Comma needs to be escaped in "list" type conformance statements

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1142]
**Describe the bug**
The user can enter values that contains the comma character, but that character is not escaped in the XML generated

**To Reproduce**
1. create a conformance statement
2. use the "Contain one of the values in the list: { 'VALUE 1', 'VALUE 2', 'VALUE N' }."
3. enter value(s) containing a comma
4. hit generate assertion button to see the XML.
5. look at the CSV attribute in the XML

**Expected behavior**
I'm not sure how , should be escaped in the XML, but I'm pretty sure it shouldn't like like what I'm seeing. 

**Screenshots**
![image](https://user-images.githubusercontent.com/13591511/93623202-5856dc00-f9ac-11ea-87ef-52ba844315ef.png)

**Comment by HossamT** [comment]
Is it realistic to expect conformance statements with commas in the values and escape them in the XML? 
Or we shouldn't even allow commas to begin with?

**Comment by carolinerosin** [comment]
you can probably prevent it in IGAMT, don't let the user do that and we'll see if someone complains

**Comment by Abdelghani90** [comment]
@carolinerosin is this fixed ?

**Comment by carolinerosin** [comment]
I don't think this was fixed, I'm still able to do that
![image](https://user-images.githubusercontent.com/13591511/105065686-20d86900-5a4c-11eb-9032-afb7e688f0db.png)

We can just not allow any value with a comma in the list (so in my latest example, don't allow the user to input "A,B")

**Comment by carolinerosin** [comment]
tested and the filter is working, but do we want to let the user know that comma isn't accepted ? 
Could be confusing since we are not giving any feedback (and the description is still updated to the value with comma)

![image](https://user-images.githubusercontent.com/13591511/107408429-f6248200-6ad8-11eb-9351-96d2abe63778.png)
