### ISSUE TITLE
[BUG] Segment does not show up in group after being "added" to custom message structure

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1145]
**Describe the bug**
Trying to create a custom segment structure. At some point I created a group, tried to add a segment to that group but the segment was no added (nothing happened)

**To Reproduce**
1. create custom message structure
2. start from MFN_Znn version 2.8.2
3. add event M18 with description "MFN/MFK – Master File Notification – Test/Observation (Payer)"
4. delete M14 / MFN/MFK - Master file notification - site defined line
5. change structure ID to MFN_M18

Note : at this point we cannot hit "submit" (it's greyed out). To be able to submit, I have to hit the blue plus button (Action) first

6. Submit

7. change the name of the group MF_SITE_DEFINED to MF_PAYER
8. Delete segment Hxx
9. add a new group in MF_PAYER. The group name is PAYER_MF_ENTRY
10. add a new segment to PAYER_MF_ENTRY. Pick segment MCP from version 2.8.2
11. add a new group after MCP, in the PAYER_MF_ENTRY group. The group name is PAYER_MF_COVERAGE
12. add a segment to PAYER_MF_COVERAGE. Pick segment PM1 from version 2.8.2

**Expected behavior**
I want to see the PM1 segment in my structure. 

**Screenshots**
![image](https://user-images.githubusercontent.com/13591511/93915763-77b87680-fcd6-11ea-92f4-161c50a69484.png)

**Additional context**
It did not happen in all groups, I was able to create the PAYER_MF_ENTRY group and add the MCP segment without having the issue

**Comment by smartinez290** [comment]
@carolinerosin I created three structures for RSP and it worked fine for me.

**Comment by ncrouzier-nist** [comment]
I'm having the "same" issue of "Invalid Location". 
In my case it just seems that anything created 3 layers deep is not working (group or segment)

![image](https://user-images.githubusercontent.com/14352180/94155322-d142b180-fe4c-11ea-8b9b-472d86e7f069.png)
In my example, I can't add anything under the group LOCATION or ALERT_OBSERVATION

**Comment by carolinerosin** [comment]
I was able to create my structure.
