### ISSUE TITLE
Default configuration Delta ON/OFF option active

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#1152]
**Describe the bug**
Default configuration Delta ON/OFF option active

**Expected behavior**
Delta On/Off is not an option in the default config, it can't be saved. Therefore, I suggest inactivate on/off selection as well as the Export Mode selection in this panel. Just like it was done for the Font. 

**Screenshots**
![image](https://user-images.githubusercontent.com/14842422/94167361-6bf5bd00-fe5a-11ea-9163-e3aeee303b0d.png)

**Additional context**

**Comment by smartinez290** [comment]
@YoussefBouij this issue is still pending.

**Comment by Abdelghani90** [comment]
@smartinez290 this is fixed. please double check
