### ISSUE TITLE
Default Export Configuration Error 

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#1153]
**Describe the bug**
I am getting an error after attempting to modify the Default Export Configuration Delta option. Error continue to show and I can't selected another cofinguration.

**To Reproduce**
1. Select IG Document Default Export
2. Click on Delta On/Off (not able to safe, no error message generated at this point)
3. Try to select a different configuration (the "The Default Configuration cannot be modified. Please create your own configuration" error message appears
4. I can't select any other configuration at this point, the error continue to appear.
5. I am able to create a new Configuration and the error stops showing up, but the previous error are still  on display.

**Screenshots**
![image](https://user-images.githubusercontent.com/14842422/94168705-e70ba300-fe5b-11ea-977b-a5fbfd390d01.png)

**Additional context**

**Comment by smartinez290** [comment]
@YoussefBouij it looks like this issue is still pending.

**Comment by Abdelghani90** [comment]
@smartinez290  do you still have this issue?
