### ISSUE TITLE
Unable to push 2.5.1 Profiles to GVT

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#1167]
Unable to push 2.5.1 Profiles to GVT, generating the following error:
![image](https://user-images.githubusercontent.com/14842422/95510481-fde5e580-0983-11eb-9c36-b753fc2c7613.png)

Per @Jungyubw 
"In the XML schema, the tool does not allow "space" for Group name.
Patient Identifier List should be no space.
Some errors for link. I think this is false error."

**Comment by Jungyubw** [comment]
@smartinez290 or @carolinerosin Please check this. I think It already fixed for this deployment
