### ISSUE TITLE
Custom Structure: Validation not generating expected error

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#1172]
**Describe the bug**
@HossamT and @Jungyubw 

The validation  is not generating the expected error on CS defined at the message level. This, Z31, Profile is using a custom structure. 

IZ-72 | PatientIdentifierList.PID-1 (Set ID - PID) shall be valued sequentially starting with the value '1'.
-- | --
The following message should generate an error and it is not.
MSH|^~\&|SOME_SYSTEM|A_Clinic |MYIIS|MyStateIIS|20091105100020-0500||RSP^K11^RSP_K11|37374859|P|2.5.1|||NE|NE|||||Z31^CDCPHINVS|A_Clinic^SOME_SYSTEM^^^^X68&&^AN^^^A_Clinic1234^
MSA|AA|793543
QAK|37374859|OK|Z34^Request Immunization History^CDCPHINVS
QPD|Z34^Request Immunization History^CDCPHINVS|37374859|123456^^^MYEHR^MR|Child^Bobbie^Q^^^^L|Que^Suzy^^^^^M|20050512|M|10 East Main St^^Myfaircity^GA^^^L
PID|1||99445566^^^MYStateIIS^SR||Child^Robert^^^^^L||20050512|M
NK1|1|Child^Susan^^^^^L|MTH^Mother^HL70063|32 Prescott Street Ave^^Warwick^MA^02452^USA^L
PID|2||123456^^^MYStateIIS^SR||Child^Robert^^^^^L||20050512|M
PID|2||123456^^^MYStateIIS^SR||Child^Robert^^^^^L||20050512|M

**To Reproduce**
Z31 XML

[HL7-Version-2.5.1-Implementation-Guide-for-Immunization-Messaging_Oct19-5f8de44c9194be0006c9b97d_20201019_203512.zip](https://github.com/usnistgov/hl7-igamt/files/5404567/HL7-Version-2.5.1-Implementation-Guide-for-Immunization-Messaging_Oct19-5f8de44c9194be0006c9b97d_20201019_203512.zip)

I

**Comment by carolinerosin** [comment]
I looked at the IG and it seems that the conformance statement was not set at the right context, this is what Chrissy needs to do

![image](https://user-images.githubusercontent.com/13591511/96598484-e92b1b00-12bc-11eb-9f67-7d886b463c6a.png)

Right now the context for IZ-72 is the root of the message.

**Comment by smartinez290** [comment]
Proposed solution tested, but getting the following error. @HossamT and @Jungyubw are looking at it. 
![image](https://user-images.githubusercontent.com/14842422/96599268-be8d9200-12bd-11eb-9b82-9ab9d4a374ce.png)

**Comment by Jungyubw** [comment]
@smartinez290 or @carolinerosin Please check this. I think It already fixed for this deployment
