### ISSUE TITLE
[BUG] IG used for IGAMT-2 QA not exporting to GVT

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1176]
**Describe the bug**
I'm trying to execute the test scenarios from Sandra. I'm using the IG named "NIST IGAMT Profiling Guide [DRAFT]" that she shared with me. I'm working from the shared IG (I did not create a clone).
When I try to export her IG to GVT, I get an error because the XML generated is invalid, so I cannot export to GVT.

**To Reproduce**
1. Open IG "NIST IGAMT Profiling Guide [DRAFT]"
2.  Click on "Connect"
3. Choose tool "GVT"
4. Set username and password, hi login
5. Select tool scope and check the "UNSOLICITED IMMUNIZATION UPDATE" conformance profile
6. Verification shows some errors and warnings, but nothing fatal, hit "Proceed anyway"
7. See screenshot

**Expected behavior**
Export the IG to GVT.

**Screenshots**
![image](https://user-images.githubusercontent.com/13591511/97022978-d7e34800-1522-11eb-9a8b-bb871b793144.png)

**Additional context**
none

**Comment by smartinez290** [comment]
@carolinerosin @Abdelghani90 I am having the same issue trying to push the 2.5.1 IG to GVT. Verification errors that were not there before are been generated.

**Comment by carolinerosin** [comment]
it is coming from dynamic mapping
![image](https://user-images.githubusercontent.com/13591511/97042911-c0668800-153f-11eb-9c76-a116dee56350.png)

how do we want to solve that ? Tell users to add the missing DT to their IGs or do we want to automatically do it (not sure if that is easy to do)? @Abdelghani90 what do you think ?

**Comment by carolinerosin** [comment]
So I added the "missing" datatypes to my IG, but it does not solve the issue. The dynamic mapping that is generated in the XML is still missing some pieces (even though the datatypes were imported in the IG)

**Comment by Abdelghani90** [comment]
@Jungyubw  would it be ok to add them from the DB? or they need to appears in other part of the XML?

**Comment by Jungyubw** [comment]
Fixed

**Comment by carolinerosin** [comment]
My test scenario I exported successfully to gvt.
With my test scenario II, I still got issues (but maybe it is something else ?). If you want me to create a separate ticket let me know.
The IG is 5f932d259194be00062e12e3 (Testing Scenario II_IG 10 23 2020) under user rosinc

![image](https://user-images.githubusercontent.com/13591511/97470272-bc5eaf80-191d-11eb-9bcf-ecd5799eb51b.png)

**Comment by Abdelghani90** [comment]
it look like IGAMT is not able to access the vocabulary service. @mellouli-dev  Please check if the vocabulary service is up and running?

**Comment by carolinerosin** [comment]
I just tried a second time and the error is gone, maybe it was the vpn or my connection, who knows !
