### ISSUE TITLE
[BUG] Name of datatype in Word export is wrong

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1177]
**Describe the bug**
I created a datatype named "CE_TXT" in my IG. When I export to Word the datatype flavor name is "CE_CE" in the datatypes sections. IT is correct in the segment where it is used

**To Reproduce**
1. create CE_TXT flavor and modify some usages
2. assign this CE_TXT flavor to a segment flavor that is used in the message definition
3. export Word
4. Go to the datatype section and check the title for "CE_TXT"

**Expected behavior**
I am expecting to see "CE_TXT" not "CE_CE"

**Screenshots**
![image](https://user-images.githubusercontent.com/13591511/97046547-8c8e6100-1545-11eb-8ff4-2fa31e460363.png)
![image](https://user-images.githubusercontent.com/13591511/97046591-9b751380-1545-11eb-9120-28192bb9cb70.png)

**Additional context**
none

**Comment by carolinerosin** [comment]
same issue in co-constraint table
![image](https://user-images.githubusercontent.com/13591511/97189042-90ef8f80-177a-11eb-8d7f-d3d5c326de65.png)

**Comment by Abdelghani90** [comment]
I fixed that, it will be deployed soon
