### ISSUE TITLE
[BUG] Cannot delete co-constraint group table

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1178]
**Describe the bug**
I created a co-constraint group. I did not add any co-constraint in it, I just tried to delete what I created, but IGAMT get stuck with the spinning wheel.

**To Reproduce**
1. Go to 'Co-Constraint Groups' section
2. Create Co-Constraint Groups
3. Right click on the group just created to delete

**Expected behavior**
I expect my co-constraint group to be deleted

**Screenshots**
From Chrome's console:
![image](https://user-images.githubusercontent.com/13591511/97186958-54229900-1778-11eb-8933-8dfccd8d7f8d.png)

**Additional context**
My IG is Testing Scenario IV_IG 10 24 2020 (5f96dcd49194be0006c50430), username rosinc if you need to go have a look there

**Comment by Abdelghani90** [comment]
@carolinerosin was this fixed?

**Comment by carolinerosin** [comment]
Nope, I still have this issue

**Comment by carolinerosin** [comment]
tested 👍
