### ISSUE TITLE
October 26 Deployment: Delta function not working

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#1183]
@Abdelghani90 @carolinerosin 
**To Reproduce**
1. Go to 'any Derived IG
2. Click on 'Delta'
The following error appears:

![image](https://user-images.githubusercontent.com/14842422/97326845-c82d7180-184a-11eb-9ce9-01eabdee35c2.png)

**Comment by smartinez290** [comment]
@mellouli-dev This is the ticket.

**Comment by Abdelghani90** [comment]
@smartinez290  I don't have this issue. can you provide more details?

**Comment by smartinez290** [comment]
@Abdelghani90 I am getting that "Page cant be loaded" message every time I click on "Delta" on a Derived IG

![image](https://user-images.githubusercontent.com/14842422/97603252-9cdd8a80-19e2-11eb-9383-465525d43695.png)

**Comment by Abdelghani90** [comment]
Fixed! it will be included in the next deployment
