### ISSUE TITLE
October 26: Dynamic Mapping

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#1186]
**Describe the bug**
The OBX Dynamic mapping is not getting updated when HL70125 flavor is updated. 

**User Account**
smartinez290

**URL**
https://hl7v2.igamt-2.nist.gov/igamt/ig/5f636abf9194be0006c64d01/segment/5f9c62239194be0006761519/dynamic-mapping

**To Reproduce**
1. Go to HL70125_TXT - 3 DT listed because I removed one
![image](https://user-images.githubusercontent.com/14842422/97750050-78f37500-1ac6-11eb-9e00-74dca2c47d10.png)

2. Click on OBX_TXT Dynamic Mapping , the original DT are still there
![image](https://user-images.githubusercontent.com/14842422/97750115-96284380-1ac6-11eb-9cf7-16b17690806a.png)

**Comment by Abdelghani90** [comment]
@smartinez290 we are not handling that !
