### ISSUE TITLE
[BUG] OBX segment not marked as "updated" when updating dynamic mapping (in a derived profile)

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1197]
**Describe the bug**
I'm working in a derived profile. I updated the dynamic mapping for OBX. The OBX segment id not highlighted (as "updated") in the left side panel when I toggle "Differential view".

**User Account**
rosinc

**URL**
https://hl7v2.igamt-2.nist.gov/igamt/ig/5ffc6a1a8b87bc00085abb44/segment/5ffc6a1a8b87bc00085abb9b/dynamic-mapping

**To Reproduce**
1. Change dynamic mapping in OBX
2. Toggle "differential view"
3. Look at left side panel ("Segment and field description" section)

**Expected behavior**
I'm expecting OBX to be flagged as updated.

**Screenshots**
![image](https://user-images.githubusercontent.com/13591511/104203245-e9d5d800-53f9-11eb-93f3-b8d441582829.png)

**Additional context**
n/a

**Comment by Abdelghani90** [comment]
We did not included the Dynamic mapping into the delta. Do we need to include it?

**Comment by carolinerosin** [comment]
I think we should. Let's bring that up in the next IGAMT meeting to see what Rob's expectations are

**Comment by carolinerosin** [comment]
Looks like this one is still active. Also I noticed that I don't even see the new value "user mapping" highlighted anymore.
I changed the mapping for CX, but it does not show as "updated"
![image.png](https://images.zenhubusercontent.com/58236f86e40e5714b16fff98/6df23d03-4a41-4699-a9c6-edec6bc1b30d)
