### ISSUE TITLE
[REQUEST] Add NotPresentBehavior attribute to XML for multiple assertions type

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1200]
**Is your feature request related to a problem? Please describe.**
We added the NotPresentBehavior attribute for the PlainText assertion a while ago. The same attribute was added to the validation for the other assertions  (Format, NumberList, StringList, SimpleValue, PathValue, ValueSet, StringFormat). We need to add this attribute to the remaining assertions in the XML serialization, using the same logic as what we did for PlainText.

**Describe the solution you'd like**
NotPresentBehavior attribute should be added to the XML generated by IGAMT for the following assertions : Format, NumberList, StringList, SimpleValue, PathValue, ValueSet, StringFormat

**Describe alternatives you've considered**
Using a "Presence" check that the user has to enter himself (so more work for the user and more complex conformance statements/ condition predicates). Also all the users are not aware that they should add the extra presence check and/or are not consistent in using it in their IGs.

**Additional context**
Reminder of the decision we made on that topic (when we worked on PlainText)
- For predicates, set the attribute to FAIL
- For CS IF THEN, set attribute to FAIL in in both parts 
- For complex CS every node under an IF THEN, set attribute to FAIL
- For other CS, set attribute to PASS

**Comment by Jungyubw** [comment]
@carolinerosin Currently, IGAMT is not using "NumberList", SimpleList", and "ValueSet". 
Others are applied.

**Comment by carolinerosin** [comment]
Awesome, let me know when this is deployed and that I can test it.

**Comment by carolinerosin** [comment]
tested 👍
