### ISSUE TITLE
[REQUEST] Modify the CommaSeparatedStringType type to allow periods.

### ISSUE THREAD

**Issue by ncrouzier-nist** [usnistgov/hl7-igamt#1214]
**Is your feature request related to a problem? Please describe.**
I'm trying to add a conformance statement with a list of OIDs but the profile validation doesn't allow list of values with "." in them

**Describe the solution you'd like**
I'd like the regex to be modified to allow periods

**Describe alternatives you've considered**
We might want to add other characters 

**Additional context**
@Jungyubw will have to update his file on his repo where the profile verification gets it's files 
https://raw.githubusercontent.com/Jungyubw/NIST_healthcare_hl7_v2_profile_schema/master/Schema/NIST%20Validation%20Schema/Expressions.xsd

**Comment by carolinerosin** [comment]
@HossamT and I are discussing at the moment if we want to open up the schema to any character. We can't remember if there was a reason to have this regex to start with. I think the regex comes from Salifou's initial implementation (maybe we added the - and _ characters to it later ?).
Anyway, we can ask Rob if he has a preference. Either just add "." or even authorize any character (get rid of the regex).

**Comment by HossamT** [comment]
Decision : 
- Add . (period)
- Add \ (backslash)

**Comment by Jungyubw** [comment]
Fixed on 
https://github.com/Jungyubw/NIST_healthcare_hl7_v2_profile_schema/blob/master/Schema/NIST%20Validation%20Schema/Expressions.xsd

**Comment by carolinerosin** [comment]
Found another issue while testing this one #1216

**Comment by Jungyubw** [comment]
@carolinerosin So this issue is okay, right?

**Comment by carolinerosin** [comment]
yes I don't get the verification error anymore
