### ISSUE TITLE
[BUG] [HIT-DEV] Issue with the 'NotPresentBehavior' attribute in StringList assertion

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1216]
**Describe the bug**
I get a schema validation error when I try to export my profile to GVT. The error is related to 'NotPresentBehavior' attribute in the StringList assertion.
I think it's the schema that wasn't updated to allow the attribute there.

**User Account**
rosinc

**URL**
https://hit-dev.nist.gov:8084/igamt/ig/6022afb6b3cb1f0007e422b8/segment/6022afd3b3cb1f0007e42cd8/conformance-statement

**To Reproduce**
1. create a conformance statement with a list of values
2. try to export to GVT

**Expected behavior**
Should be exported with no schema error

**Screenshots**
![image](https://user-images.githubusercontent.com/13591511/107391397-a50b9280-6ac6-11eb-89a7-a464ac2172b4.png)

And here's the assertion (this is correct)
![image](https://user-images.githubusercontent.com/13591511/107391878-22370780-6ac7-11eb-8c9a-cd60a52ea547.png)

**Comment by Jungyubw** [comment]
@carolinerosin Okay I will update the schema.

**Comment by carolinerosin** [comment]
@Jungyubw I didn't check the other assertion types, but I would think you need to add that to others as well.
You can add to the following : Format, NumberList, StringList, SimpleValue, PathValue, ValueSet, StringFormat because this is what is handled by validation.

@HossamT can double check what if I'm saying is correct :D

**Comment by Jungyubw** [comment]
@carolinerosin I have fixed to add and checked "NotPresentBehavior" for PathValue, PlainText, StringFormat, Format, NumberList, StringList, SimpleValue, and ValueSet (Now all of types have this optional 'NotPresentBehavior' except to presence).



Here is part of Expressions:

<xs:complexType name="PresenceType">
		<xs:attribute name="Path" type="PathType" use="required" />
	</xs:complexType>
	
	<xs:complexType name="PathValueType">
		<xs:attribute name="Path1" type="PathType" use="required" />
		<xs:attribute name="Operator" type="OperatorType" use="required" />
		<xs:attribute name="Path2" type="PathType" use="required" />
		<xs:attribute name="NotPresentBehavior" type="BehaviorType" use="optional" />
	</xs:complexType>
	
	
	
	
	
	<xs:complexType name="PlainTextType">
		<xs:attribute name="Path" type="PathType" use="required" />
		<xs:attribute name="Text" type="NonEmptyString" use="required" />
		<xs:attribute name="IgnoreCase" type="xs:boolean" use="optional" />
		<xs:attribute name="AtLeastOnce" type="xs:boolean" use="optional" />
		<xs:attribute name="NotPresentBehavior" type="BehaviorType" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="StringFormatType">
		<xs:attribute name="Path" type="PathType" use="required" />
		<xs:attribute name="Format" type="NonEmptyString" use="required" />
		<xs:attribute name="AtLeastOnce" type="xs:boolean" use="optional" />
		<xs:attribute name="NotPresentBehavior" type="BehaviorType" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="FormatType">
		<xs:attribute name="Path" type="PathType" use="required" />
		<xs:attribute name="Regex" type="NonEmptyString" use="required" />
		<xs:attribute name="AtLeastOnce" type="xs:boolean" use="optional" />
		<xs:attribute name="NotPresentBehavior" type="BehaviorType" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="NumberListType">
		<xs:attribute name="Path" type="PathType" use="required" />
		<xs:attribute name="CSV" type="CommaSeparatedNumberType" use="required" />
		<xs:attribute name="AtLeastOnce" type="xs:boolean" use="optional" />
		<xs:attribute name="NotPresentBehavior" type="BehaviorType" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="StringListType">
		<xs:attribute name="Path" type="PathType" use="required" />
		<xs:attribute name="CSV" type="CommaSeparatedStringType" use="required" />
		<xs:attribute name="IgnoreCase" type="xs:boolean" use="optional" />
		<xs:attribute name="AtLeastOnce" type="xs:boolean" use="optional" />
		<xs:attribute name="NotPresentBehavior" type="BehaviorType" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="SimpleValueType">
		<xs:attribute name="Path" type="PathType" use="required" />
		<xs:attribute name="Operator" type="OperatorType" use="required" />
		<xs:attribute name="Value" type="NonEmptyString" use="required" />
		<xs:attribute name="Type" type="ValueType" default="String" />
		<xs:attribute name="NotPresentBehavior" type="BehaviorType" use="optional" />
	</xs:complexType>
	
	<xs:complexType name="ValueSetType">
		<xs:attribute name="Path" type="PathType" use="required" />
		<xs:attribute name="ValueSetID" type="xs:string" use="required" />
		<xs:attribute name="BindingStrength" type="BindingStrengthType" use="required" />
		<xs:attribute name="BindingLocation" type="BindingLocationType" use="required" />
		<xs:attribute name="NotPresentBehavior" type="BehaviorType" use="optional" />
	</xs:complexType>

**Comment by carolinerosin** [comment]
@HossamT can you help on that one ?

**Comment by carolinerosin** [comment]
maybe we should revisit that idea of having only one repository with the schemas

**Comment by Jungyubw** [comment]
@HossamT @carolinerosin  Currently most of resource bundle are associated with "https://github.com/Jungyubw/NIST_healthcare_hl7_v2_profile_schema"

so...

(1) Check history of changes of 'v2-validation-legacy'
(2) Merge the changes from 'v2-validation-legacy' to 'NIST_healthcare_hl7_v2_profile_schema'
(3) Update 'v2-validation-legacy' as same as 'NIST_healthcare_hl7_v2_profile_schema'
(4) Update all of Resource bundles, Tools (GVT, TCAMT, IGAMT-1, IGAMT-2) to using "v2-validation-legacy"

If you agree, I will do...

**Comment by HossamT** [comment]
@Jungyubw I agree on the merge part, but maybe we should create a repo that belongs to usnistgov that contains the schema only. 
It might create problems if you refer to the schema by URL in other tools though, so may be we need to keep it there in your account until we do an inventory of all the places that URL is used

**Comment by carolinerosin** [comment]
I think we started to create a repo at some point and wanted to wait for @Jungyubw to be back. 
here is it, do you want to use this repo ? https://github.com/usnistgov/hl7-schemas

the schemas for validation and verification should go under "NIST HL7 v2 schemas"

**Comment by Jungyubw** [comment]
@carolinerosin I agree on. I will make "NIST HL7 v2 schemas" in the https://github.com/usnistgov/hl7-schemas.
Before applying the schema location for tools and resource bundle, we should make sure all changes are correctly included. I will make a merge commit on https://github.com/usnistgov/hl7-schemas, then let's discuss again.

**Comment by carolinerosin** [comment]
sounds good !

**Comment by Jungyubw** [comment]
@carolinerosin @HossamT 

I have updated my XSDs from changes of Hossam's ones. Here is my changes:
https://github.com/Jungyubw/NIST_healthcare_hl7_v2_profile_schema/commit/a86ab2eeafd72fe573cee073cffbcad70b3d8d27

Also I have added same XSD in the "NIST HL7 v2 schemas/Legacy" and  made pull-request. @carolinerosin Please review it and approved if you don't have any issue.

**Comment by Jungyubw** [comment]
@carolinerosin Please review the NIST HL7 v2 schemas/Legacy/NIST Validation Schema. 

Other folders are for Gazelle and NIST Display schema. There is no change but I think we need them in the same repo.

**Comment by Jungyubw** [comment]
@HossamT 

Please update your Expressions.xsd.
Line 35:  			<xs:pattern value="[0-9a-zA-Z\-_]+(( *),( *)[0-9a-zA-Z\-_]+)*" />
![image](https://user-images.githubusercontent.com/13385213/107422887-a4d0be80-6ae9-11eb-87d1-b925ec5a0baa.png)

**Comment by carolinerosin** [comment]
@Jungyubw OK, I'll review the schemas today.
