### ISSUE TITLE
[BUG] Conditional conformance statement assertion is incorrect

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1217]
**Describe the bug**
The "THEN" part of the conditional assert is missing for the XML generation when the user choses "contain the value ‘VALUE’ (DESCRIPTION) drawn from the code system 'CODE SYSTEM'."

**User Account**
rosinc

**URL**
https://hit-dev.nist.gov:8084/igamt/ig/6022afb6b3cb1f0007e422b8/segment/6022b51db3cb1f0007e4d117/conformance-statement

**To Reproduce**
1. create conditional conformance statement
2. choose an IF assertion
3. choose the THEN assertion "contain the value ‘VALUE’ (DESCRIPTION) drawn from the code system 'CODE SYSTEM'."
4. click on Generate Assertion (see screenshot)

**Expected behavior**
The IMPLY is missing the second part.

**Screenshots**
![image](https://user-images.githubusercontent.com/13591511/107394399-d3d73800-6ac9-11eb-8cfb-dc8b680d7241.png)

**Additional context**

**Comment by carolinerosin** [comment]
same thing for this one 
![image](https://user-images.githubusercontent.com/13591511/107395927-4694e300-6acb-11eb-8554-3eac811d33c1.png)

**Comment by Jungyubw** [comment]
@carolinerosin I think #1202 and this come from same issue.... I will check it.

**Comment by Jungyubw** [comment]
@carolinerosin I have checked this again after fixed #1202 . The error is gone for your example.
