### ISSUE TITLE
[BUG] XML reserved characters do not seem to be escaped correctly

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1220]
**Describe the bug**
Looks like XML reserved characters are not properly escaped in the the XML generation of conformance statements.

**User Account**
rosinc

**URL**
https://hl7v2.igamt-2.nist.gov/igamt/ig/602c448b8b87bc000764bb4f/datatype/602eb5938b87bc000765161b/conformance-statement
**To Reproduce**
1. Create a conformance statement or condition predicate
2. Use one of the XML reserved characters in the "value" of the conformance statement (for example > or < )
3. Click on Generate assertion

**Expected behavior**
XML reserved characters should be properly escaped to avoid generating invalid XML.

**Screenshots**
![image](https://user-images.githubusercontent.com/13591511/108419344-667d8280-7200-11eb-9de3-ffc665d6df64.png)

![image](https://user-images.githubusercontent.com/13591511/108419754-ec99c900-7200-11eb-8d66-b8ab5978453d.png)

**Comment by Jungyubw** [comment]
@carolinerosin 

I will make it to handle below 4 chars for XML
![image](https://user-images.githubusercontent.com/13385213/108529638-abf28c00-72a2-11eb-8e92-368e38502ab2.png)

**Comment by carolinerosin** [comment]
I think there is also the apostrophe

![image](https://user-images.githubusercontent.com/13591511/108530863-0b9d6700-72a4-11eb-9ddb-43c9f41778ec.png)

source : https://www.w3resource.com/xml/reserved-markup-characters.php

**Comment by Jungyubw** [comment]
Oh yes...one row is hidden by google...

**Comment by Jungyubw** [comment]
It is done ...

![image](https://user-images.githubusercontent.com/13385213/108535404-4d7cdc00-72a9-11eb-810f-8f2a45e63a68.png)

**Comment by carolinerosin** [comment]
awesome ! we can move it to QA then and I'll double check after the next deployment.
