### ISSUE TITLE
[BUG] Add verification check to value set codes with whitespace (informational)

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1231]
**Describe the bug**
Verification should add a check in value sets to verify that a code does not contain a whitespace. The classification is "informational".

**User Account**
n/a

**URL**
n/a

**To Reproduce**
you can check with HL7 table 0211 for example.

**Expected behavior**
verification should flag codes in values sets that contain a whitespace

**Screenshots**
n/a

**Additional context**
Discussed with Rob on 03/08/2021 IGAMT meeting

**Comment by Jungyubw** [comment]
Fixed..Also I added same checking for codesystem.

![image](https://user-images.githubusercontent.com/13385213/111189386-687efb00-858c-11eb-9235-d32bf98edb8a.png)
