### ISSUE TITLE
[BUG] Fix value set binding for HL7 segments using CQ

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1237]
**Describe the bug**
The datatype CQ has a value set binding defined at the field level in several HL7 segment. This binding needs to be moved down to component 2 (but from each segment's level, not in the datatype)

**User Account**
n/a

**URL**
n/a

**To Reproduce**
Open a message structure that uses a segment with a "CQ" field. For example RCP segment (in the IZ guide) has the issue.

**Expected behavior**
Here's the list of segments/versions to fix

Segment:  ADJ
HL7 versions: 2.6 2.7 2.7.1 2.8 2.8.1 2.8.2
Move HL70560 binding from ADJ-6 to ADJ-6.2, with default binding location set to "1".

Segment:  CDO
HL7 versions: 2.8 2.8.1 2.8.2
Move HL70924 binding from CDO-4 to CDO-4.2, with default binding location set to "1".

Segment:  PSL
HL7 versions: 2.6 2.7 2.7.1 2.8 2.8.1 2.8.2
Move HL70560 binding from PSL-12 to PSL-12.2, with default binding location set to "1".

Segment:  QRD
HL7 versions: 2.3.1 2.4 2.5 2.5.1 2.6
Move HL70126 binding from QRD-7 to QRD-7.2, with default binding location set to "1".

Segment:  RCP
HL7 versions: 2.4 2.5 2.5.1 2.6 2.7 2.7.1 2.8 2.8.1 2.8.2
Move HL70126 binding from RCP-2 to RCP-2.2, with default binding location set to "1".

**Screenshots**
RCP example: remove value set binding from RCP-2 and put it on RCP-2.2, with binding location [1]
![image](https://user-images.githubusercontent.com/13591511/113767041-2c9f0780-96ec-11eb-80c9-204342844e78.png)

**Additional context**

**Comment by Abdelghani90** [comment]
@HossamT @carolinerosin Do we need to apply the change to USER segment as well?

**Comment by carolinerosin** [comment]
I would say no. We will fix user segments case by case if they have issues.
