### ISSUE TITLE
[BUG] Profile component items not showing

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1255]
**Describe the bug**
The profile component items do not show up in the table (after navigating somewhere else). I can see them in the tree view.

**User Account**
rosinc

**URL**
https://hit-dev.nist.gov:8084/igamt/ig/6082ddbfb3cb1f000849b76d/profilecomponent/6082e29cb3cb1f000849c05e/segment/6082de77b3cb1f000849c033/structure

**To Reproduce**
Not sure how I made them disappear, but I just created them, navigated somewhere else, and poof, they where gone

**Expected behavior**
they should still be in the table

**Screenshots**

![image](https://user-images.githubusercontent.com/13591511/115898624-c32d3180-a42b-11eb-8aa8-b6c3a7ac930e.png)

![image](https://user-images.githubusercontent.com/13591511/115898701-d9d38880-a42b-11eb-8ea0-d1218a4d52e4.png)

**Additional context**

**Comment by Abdelghani90** [comment]
![Screen Shot 2021-04-23 at 12 13 13 PM](https://user-images.githubusercontent.com/16800878/115899899-587cf580-a42d-11eb-83b7-718ef8af6ceb.png)
I think this happen every time when you select the root (see picture).
If you have previously defined items in obx-1 .. they will dissapear as soon as you add the OBX item

**Comment by carolinerosin** [comment]
Yes I think I tried to add the root, so that's how you can reproduce it

**Comment by carolinerosin** [comment]
then I tried to go to conformance statements, but I guess it wasn't implemented yet :D

**Comment by Abdelghani90** [comment]
yes this is not implemented yet :)
