### ISSUE TITLE
[BUG] Push to GVT is not working for composite profiles

### ISSUE THREAD

**Issue by Abdelghani90** [usnistgov/hl7-igamt#1257]
**Describe the bug**
Pushing to GVT is not working for composite profiles.
**User Account**
ANY
**URL**
ANY
**To Reproduce**
1. Create a profile component and composite profile
2. Connect to GVT
3. The tool is looking for a conformance profile with wrong extension
4. See pictures 
<img width="1419" alt="Screen Shot 2021-04-26 at 11 22 48 AM" src="https://user-images.githubusercontent.com/16800878/116111784-f74f5f00-a684-11eb-9b55-526f091643c6.png">
<img width="1440" alt="Screen Shot 2021-04-26 at 11 22 37 AM" src="https://user-images.githubusercontent.com/16800878/116111787-f7e7f580-a684-11eb-8acb-02aad11a2cf6.png">

**Comment by Jungyubw** [comment]
This was already fixed
