### ISSUE TITLE
[BUG] Value set gets "reset" in profile component when I change the usage of the item

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1258]
**Describe the bug**
I changed a value set of a profile item in my PC. Then I changed the usage of the same item. The value set went back to the original value.

**User Account**
rosinc

**URL**
https://hit-dev.nist.gov:8084/igamt/ig/6082ddbfb3cb1f000849b76d/profilecomponent/6082e2b0b3cb1f000849c05f/segment/6082df2eb3cb1f000849c03f/structure

**To Reproduce**
1. change value set to "VPD specimen condition", change strength to "required"
2. Save (or not - does not matter)
3. change usage of the same element.

**Expected behavior**
value set binding should remain

**Screenshots**
![image](https://user-images.githubusercontent.com/13591511/116113479-8741d880-a686-11eb-9f4b-027eeaf3064a.png)
![image](https://user-images.githubusercontent.com/13591511/116113587-9b85d580-a686-11eb-9e8c-f6b6c2fc8cbb.png)
![image](https://user-images.githubusercontent.com/13591511/116113656-ae98a580-a686-11eb-8912-dec160ebbeae.png)

**Additional context**
save action does not seem to make a difference. I haven't tried with other elements (only usage and value set)

**Comment by carolinerosin** [comment]
If I change the user first and then value set, everything looks good
![image](https://user-images.githubusercontent.com/13591511/116114237-2c5cb100-a687-11eb-987d-d7f272bf881d.png)

**Comment by carolinerosin** [comment]
And it only seems to affect value set bindings. I tried with cardinality and datatype flavor, everything works

**Comment by Abdelghani90** [comment]
Fixed
