### ISSUE TITLE
Cannot PUSH Composite profile TO GVT 

### ISSUE THREAD

**Issue by Abdelghani90** [usnistgov/hl7-igamt#1263]
**Describe the bug**
The issue occurs when the profile component contains a predicate
**User Account**
ANY
**URL**
ANY
**To Reproduce**
1. Create A VXU 2.5.1 profile
2. Create a profile componenet for RXA-5.6 and add any simple predicate.
3. Push to GVT

![Screen Shot 2021-04-28 at 1 22 21 PM](https://user-images.githubusercontent.com/16800878/116446796-5055f900-a825-11eb-9d83-53ee083bc3fd.png)
![Screen Shot 2021-04-28 at 1 23 07 PM](https://user-images.githubusercontent.com/16800878/116446798-51872600-a825-11eb-8c4a-8ee2c6e33b5a.png)

**Comment by Jungyubw** [comment]
fixed
