### ISSUE TITLE
[REQUEST] In profile verification, display FATAL on top

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1278]
**Is your feature request related to a problem? Please describe.**
I think it would be nice to se FATAL on top, then ERROR, then WARNING.
FATAL are the most important for the user to fix, so they should be on top.

**Describe the solution you'd like**
By default order by severity (worst ones first).

**Describe alternatives you've considered**
n/a

**Additional context**
![image](https://user-images.githubusercontent.com/13591511/122421585-7876f400-cf5a-11eb-8770-248ef374ad98.png)

**Comment by carolinerosin** [comment]
Follow up discussion (after IGAMT meeting)
- Any FATAL error should prevent the user from exporting to GVT
- Export to XML is possible, even with FATAL errors
- When a profile has FATAL errors, only show them (no need to show lower levels)
- @ncrouzier-nist and @carolinerosin to think about hove to improve the UI

**Comment by Jungyubw** [comment]
Okay I will fix UI and logic for Fatal.

**Comment by Jungyubw** [comment]
@carolinerosin I am working on it.

I think it is better to divide the FATAL table from the others, in order to make clear the user. What do you think of?

**Comment by carolinerosin** [comment]
yes I think it is a good idea. Anything FATAL should be "more visible" because it is really something the user needs to check
