### ISSUE TITLE
[BUG] Verification (verify button) not catching errors in segment flavors generated by profile component

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1290]
**Describe the bug**
Verification does not seem to catch errors on generated segments (from profile components) when the user uses the "verify" button.
The errors are caught when exporting (to xml).

**User Account**
rosinc

**URL**
https://hit-dev.nist.gov:8084/igamt/ig/60d5e9a0b3cb1f0007b2b16c/profilecomponent/60d6212cb3cb1f0007b30ace/segment/60d6210cb3cb1f0007b30ac4/structure

**To Reproduce**
1. create profile component and composite profile
2. in profile component, change something that will trigger a verification error. For example set min cardinality to 1, max to 0
3. use verify button : no error related to that
4. export the composite profile : the verification catches the issues

**Expected behavior**
Verification should also check flavors coming from profile components when the user uses the verify button (not only at export)

**Screenshots**
profile component with error 
![image](https://user-images.githubusercontent.com/13591511/123475557-8d423000-d5c9-11eb-9513-0897e1fa75f2.png)

Verify button: no error related to my profile component
![image](https://user-images.githubusercontent.com/13591511/123475689-be226500-d5c9-11eb-95af-f89d8dfc6f8c.png)

XML export of composite profile:
![image](https://user-images.githubusercontent.com/13591511/123475773-df835100-d5c9-11eb-84a4-700003f59312.png)

**Additional context**
n/a

**Comment by Jungyubw** [comment]
@carolinerosin I will add functionality to consider to check objects generated by profile-component.
