### ISSUE TITLE
[BUG]Co-Constraint table grouper

### ISSUE THREAD

**Issue by Abdelghani90** [usnistgov/hl7-igamt#1300]
**Describe the bug**
The Co-constraint grouper column is not set to OBX-4 when the constraint table contains only external groups.

**User Account**
Any
**URL**
Any
**To Reproduce**
1. Create an empty co-constraint table 
2. Create co constraint group
3. Import the co-constraint group

**Expected behavior**
The the column "Group by" should contain OBX-4 by default. which would appear as soon as the user add an internel group.

**Comment by HossamT** [comment]
When importing a co-constraint group, the group's grouper should be used in no grouper was defined for the table.
If both the group and the table have no grouper, it should be added manually or caught by the verification.
Implementing something else would add complexity to the implementation.

Related bug fix : 
- When a co-constraint group is created on an OBX segment, set the grouper as OBX-4
