### ISSUE TITLE
[BUG] XML characters not escaped correctly in "generate assertion"

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1319]
**Describe the bug**
I created a conformance statement that contains XML reserved characters (< > etc). When I click on "generate assertion" the XML produced is not valid because the characters are not escaped.

**User Account**
rosinc

**URL**
https://hl7v2.igamt-2.nist.gov/igamt/ig/604633a28b87bc000810eecd/datatype/604689908b87bc00081136f8/conformance-statement

**To Reproduce**
1. Create conformance statement (I used "contain one of the values in the list")
2. add a value with an reserved character
3. check the assertion by clicking on "generate assertion"

**Expected behavior**
XML special characters should be escaped to generate valid XML.

**Screenshots**
![image](https://user-images.githubusercontent.com/13591511/127010410-f0ba6733-7001-44f6-9067-315d135010b7.png)

**Additional context**
![image](https://user-images.githubusercontent.com/13591511/127011597-ca5c5b72-1447-4472-94c3-6d545cc52545.png)
source : https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-reserved-xml-characters-in-project-files?view=vs-2019

**Comment by Jungyubw** [comment]
I think it was fix. Let me check

**Comment by Abdelghani90** [comment]
I guess it was fixed only for single values.

**Comment by Jungyubw** [comment]
fixed
