### ISSUE TITLE
[BUG] Cannot export my IG to XML

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1331]
**Describe the bug**
I get an error when trying to export to XML

`{"status":"FAILED","type":null,"text":"Tried to insert a null child in the tree","resourceId":null,"hide":false,"date":null,"data":null}`

**User Account**
rosinc

**URL**
https://hl7v2.igamt-2.nist.gov/igamt/ig/610841518b87bc0008787276/conformanceprofile/610841ca8b87bc000878844f/structure

**To Reproduce**
1. Go to the IG linked above (Electronic Laboratory Reporting (ELR))
2. Click on Export > XML

**Expected behavior**
the IG should export in XML

**Screenshots**
![image](https://user-images.githubusercontent.com/13591511/128238957-e24f9269-007a-4134-bd88-699d2bcaf33b.png)

**Additional context**
Verification does not catch any fatal error, so everything looks good.
Export to GVT seems to work, but I don't see all my conformance statements there. If think it is missing the ones with Free Text + XML script

**Comment by Abdelghani90** [comment]
@Jungyubw Please check this issue

**Comment by Jungyubw** [comment]
@Abdelghani90 I fixed but need to check again, Could you provide  the latest DB for me via slack?

**Comment by Jungyubw** [comment]
fixed
