### ISSUE TITLE
[BUG] Value set export as CSV not working for some value sets

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1334]
**Describe the bug**
I created a PHINVADS value set (with codes) and wanted to export it as CSV. I get an error message.

**User Account**
rosinc

**URL**
https://hl7v2.igamt-2.nist.gov/igamt/api/valuesets/exportCSV/612e3f1d8b87bc0008d44f3f

**To Reproduce**
1. Go to value sets
2. Add PHINVADS value set. I picked PHVS_VISVaccines_IIS
3. Import as flavor and include codes
4. Right click on the value set and choose "Export CSV file"

**Expected behavior**
I should get a CSV file.

**Screenshots**
![image](https://user-images.githubusercontent.com/13591511/131523508-51585c04-c36e-4639-a62c-8e95f4a4aee1.png)

**Additional context**
Exporting HL7 value sets looks fine
Exporting a flavor of an HL7 value set looks fine as well

I have not tested yet with a value set imported from CSV or one created from scratch.

**Comment by Jungyubw** [comment]
Due to missing usage. I made default code usage is P
