### ISSUE TITLE
[BUG] IGAMT-2 slow after importing a CSV value set

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1338]
**Describe the bug**
I imported a value set (CSV file) and suddenly the too is slow. Not sure if it is because of the value set size or something else ? (1200 codes)

**User Account**
rosinc

**URL**
https://hl7v2.igamt-2.nist.gov/igamt/ig/610841518b87bc0008787276/valueset/613b96cf8b87bc0008d90fb8/structure

**To Reproduce**
1. import value set provided as CSV file
2. try to navigate to another page, then go back to this value set

**Expected behavior**
other value sets don't show this behavior, so i'm expecting the tool not to "hang"

**Screenshots**
n/a

**Additional context**
CSV file
[Specimen Type Value Set - PHVS_Specimen_CDC.csv](https://github.com/usnistgov/hl7-igamt/files/7145476/Specimen.Type.Value.Set.-.PHVS_Specimen_CDC.csv)

**Comment by Jungyubw** [comment]
The current limit of numbers is 500, but I think 1200 codes should be okay. I will look at it.

**Comment by carolinerosin** [comment]
well, I am able to import the codes, but it's just super slow

**Comment by Abdelghani90** [comment]
Added a pagination ( 50 code per page) and it is much better now.
