### ISSUE TITLE
[BUG] Cannot change the flavor of a specific segment

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1368]
**Describe the bug**
I try to change the flavor of my PV1 segment, but every time I save it reverts back to the HL7 object.

**User Account**
rosinc

**URL**
[The URL copied from the browser when the issue occurs.
](https://hl7v2.igamt-2.nist.gov/igamt/ig/61856cdf8b87bc00071c6113/conformanceprofile/618beb498b87bc00068e2bbe/structure)

**To Reproduce**
1. Open group PATIENT/PATIENT_VISIT
2. change flavor of PV1 to PV1_LOI
3. save
4. look at the segment : it's back to the HL7 one

**Expected behavior**
PV1 flavor should be saved.

**Screenshots**
![image](https://user-images.githubusercontent.com/13591511/141158790-6a4dacae-1195-460a-94dd-8c3a8e558b3e.png)
![image](https://user-images.githubusercontent.com/13591511/141158901-d9f77876-a976-4fd7-ab7b-ee0b3607309d.png)

After hitting save:
![image](https://user-images.githubusercontent.com/13591511/141158972-1097b6e5-170d-4eb6-8365-63a93946dbff.png)

**Additional context**
Seems specific to that IG and segment. I was able to change flavors of all others segments.
I also tried creating another flavor (PV1_XXX) and used that one instead of PV1_LOI and I had the same issue.

**Comment by Abdelghani90** [comment]
@carolinerosin  Do you still have this issue? I see that you managed to change the flavor in your IG

**Comment by carolinerosin** [comment]
@Abdelghani90 yep, still the same issue, the PV1 flavor, I haven't changed it
