### ISSUE TITLE
[BUG] Generated invalid assertion in conformance statement

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1370]
**Describe the bug**
I was able to generate an assertion (for a conformance statement) that does not pass the schema validation.

**User Account**
rosin

**URL**
https://hl7v2.igamt-2.nist.gov/igamt/ig/61856cdf8b87bc00071c6113/compositeprofile/618c20af8b87bc00068eb7fd/structure

**To Reproduce**
1. Create a conformance statement like that one (using "contain one of the values in the list")
`MSH-2 (Encoding Characters) shall contain one of the values in the list: ['^~\&','^~\&#']. 
`
2. Click on 'Verify": no error reported
3. Click on "Connect" and try to push to GVT
![image](https://user-images.githubusercontent.com/13591511/141186395-22773140-f7b7-44c1-866a-072e8c8b3551.png)

**Expected behavior**
Few things:
1. the UI should not let me enter invalid data
2. verification should catch invalid inputs as well

**Screenshots**
![image](https://user-images.githubusercontent.com/13591511/141186586-a5f472d1-e48a-4b95-81c4-79ab3dc7fafb.png)
![image](https://user-images.githubusercontent.com/13591511/141186715-3916309c-965a-450c-a065-e90be98d1b61.png)
![image](https://user-images.githubusercontent.com/13591511/141186504-ea46c664-81a7-4ac9-84ba-a9b9941e75bd.png)

**Additional context**
none

**Comment by Jungyubw** [comment]
fixed
