### ISSUE TITLE
[REQUEST] Cannot export my IG to XML or GVT

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1386]
**Describe the bug**
I get an error when I try to push to GVT or export XML

**User Account**
rosinc

**URL**
https://hl7v2.igamt-2.nist.gov/igamt/ig/61856cdf8b87bc00071c6113/conformanceprofile/618beb498b87bc00068e2bbe/structure

**To Reproduce**
1. Connect to GVT or export XML

**Expected behavior**

**Screenshots**
GVT
![image](https://user-images.githubusercontent.com/13591511/147274238-9b23274b-7825-40d8-be4b-f0b3fc7e73c9.png)
![image](https://user-images.githubusercontent.com/13591511/147274330-f689a791-ec7e-4836-82b6-eccbc209c856.png)

export to XML
![image](https://user-images.githubusercontent.com/13591511/147274465-c33fbe9b-e7bf-41df-96f3-5ba283b4eab3.png)

**Additional context**
n/a

**Comment by Jungyubw** [comment]
The issue is due to not wellformed XML in free CS. 
User need to provide valid XML for free CS/CP. Even though user does not, the tool should ignore invalid XML and produce whole XML. I modified.

Also I need to implement verification logic to catch invalid XML of free CS/CP.
