### ISSUE TITLE
[BUG] [URGENT] Error 413 Request Entity Too Large when trying to add code to value set

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1388]
**Describe the bug**
This bug was reported by Lori.
She is trying to add a value to an existing value set flavor. When saving, she gets an error saying "Http failure response for https://hl7v2.igamt-2.nist.gov/igamt/api/valuesets/6189fa048b87bc000687d707?dId=6189fa048b87bc000687d6fb: 413 Request Entity Too Large"

**User Account**
lori's account, but you can reproduce with any account, You can use mine as well (rosinc)

**URL**
here's the link under my account:
https://hl7v2.igamt-2.nist.gov/igamt/ig/61e831ae8b87bc000722e057/valueset/61e831ae8b87bc000722e065/structure

**To Reproduce**
1. Go to 'HL70396_IZ' (or just create a flavor of HL70396 in any IG)
2. Add a value to that value set
3. Try to save.

**Expected behavior**
Value should be saved with no error.

**Screenshots**
![image](https://user-images.githubusercontent.com/13591511/150168700-b2010f33-630a-42d0-93c3-b3a2f4b49bd2.png)

**Additional context**
Initial value set has 681 codes.
Exporting CSV, adding code by hand then re-importing is a workaround for the moment.

**Comment by Jungyubw** [comment]
@carolinerosin It should be fixed before. The save of valueset is working at my side.
#1385 is that what I made a fix before. And it was merged to 'develop' brach.

@Abdelghani90 this fix was deployed on prod?

Thanks.

**Comment by Abdelghani90** [comment]
@Jungyubw that's another error, the fix is was deployed.

**Comment by Jungyubw** [comment]
@Abdelghani90 need more explanation.
I export CSV from the that valueset and import it into my local (develop). It works.

**Comment by Jungyubw** [comment]
@carolinerosin Yes...I meant when I import CSV (HL70396_IZ) and add the code. The saving function is working at my local (develop)

**Comment by Jungyubw** [comment]
The number of Codes is 681

**Comment by Abdelghani90** [comment]
@carolinerosin Fixed!
