### ISSUE TITLE
[BUG] Reference to segment is not correct in XML when using custom segment

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1414]
**Describe the bug**
In the Message, the reference is OBX_LRI, but in the Segments section of the XML it is "OBX_#LRI_LRI".

**User Account**
rosinc

**URL**
https://hl7v2.igamt-2.nist.gov/igamt/ig/62322a038b87bc0007b24d8a/segment/6233479d8b87bc0007b28b5a/structure

**To Reproduce**
1. go to my ig
2. export xml
3. look at the OBX references

**Expected behavior**
the id should be the same in the XML, otherwise validation will not work. I think this should be a FATAL error (but it's not even marked in verification), because the references in the xml file are "broken".

**Screenshots**
![image](https://user-images.githubusercontent.com/13591511/159073765-e52e4114-a6ba-4eb6-8dc9-835a62ccc761.png)

**Additional context**

[Lab-Results-Interface--Release-1--DSTU-Release-2-[September-2015]-62322a038b87bc0007b24d8a_20220318_194445.zip](https://github.com/usnistgov/hl7-igamt/files/8307247/Lab-Results-Interface--Release-1--DSTU-Release-2-.September-2015.-62322a038b87bc0007b24d8a_20220318_194445.zip)

**Comment by Jungyubw** [comment]
Fixed
