### ISSUE TITLE
[BUG] Conformance statements UI: Target Occurrence Declarative Statement not always present for repeating elements

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1447]
**Describe the bug**
I'm not sure if this is a bug or by design.

If I create a CS from the message level, I go to a field that is in a segments and/or group that repeats (the filed itself isn't repeatable). There is no "Target Occurrence Declarative Statement". 

**User Account**
any account/any IG

**URL**
any IG

**To Reproduce**
1. Go to a message profile
2. create CS at the message lever, pick a field in a repeatable segment or group (example : ORU R01 message, pick OBX-3.1)
3. there is no way of choosing "at least one" etc.

**Expected behavior**
User should see "Target Occurrence Declarative Statement". 

**Screenshots**
![image](https://user-images.githubusercontent.com/13591511/170316129-05ebfc8b-dd41-48b9-89c8-33f780e80505.png)

![image](https://user-images.githubusercontent.com/13591511/170316237-0337adbb-9aa8-4c73-90d4-5322a30c6479.png)

**Additional context**
n/a

**Comment by HossamT** [comment]
When something repeats inside of other repeating elements, only allow Target Occurrences that do not select a specific instance. 
"at least once" or "no occurrence" or "x occurrence" or "all occurrence"
