### ISSUE TITLE
[BUG] Message profile export could be cleaned up

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1450]
**Describe the bug**
Email from Craig Newman:

In the message level conformance profiles, there are a few things that could be cleaned up.

“PreDefinition” is a good label in the tool, but I’m not sure we need it as a section label in the actual export. At least, a more user friendly label might be better. Not sure people will like “PreDefinition”

As well, the message name seems to have the message type, event and structure repeated. I don’t know if one is coming from the Profile Name and one from the message the profile is based on, but if there’s a way to clean this up (even with some help text on how to name a profile) it would be good.

![image](https://user-images.githubusercontent.com/13591511/170773932-f00bee1e-e656-4ded-b9ec-b02e4753f26e.png)

**User Account**
n/a

**URL**
n/a

**To Reproduce**
n/a

**Expected behavior**
n/a

**Screenshots**
n/a

**Additional context**
n/a

**Comment by carolinerosin** [comment]
06/06 decision:
- remove the label "PreDefinition" from the export (Word, PDF)
- remove the label "PostDefinition" from the export (Word, PDF)

Also: need to investigate why Craig sees the duplicated messagetype^event^structure. It does not show up in other IGs.

**Comment by Abdelghani90** [comment]
it Looks like the text of the pre def and post def got removed as well. We need to remove only the label
