### ISSUE TITLE
[BUG] Export of datatype part of OBX dynamic mapping

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1488]
**Describe the bug**
Looks like the default export configuration does not include the datatypes from the OBX dynamic mapping.

**User Account**
rosinc

**URL**
https://hl7v2.igamt-2.nist.gov/igamt/ig/5fad49c99194be00066f5034/segment/5fad49c99194be00066f5093/structure

**To Reproduce**
1. Export HTML
2. Customize
3. Look at datatypes, for example DT should be checked because it is part of OBX_IZ03 dynamic mapping

**Expected behavior**
the default export configuration should include the datatypes that are part of any OBX or OBX flavor, for all OBX flavors that are part of the export

**Screenshots**
![image](https://user-images.githubusercontent.com/13591511/186017889-6fdf709f-36c9-4526-8be8-8af51ea889a8.png)

![image](https://user-images.githubusercontent.com/13591511/186018000-a61588ac-f09e-4773-ae56-fe11a3a9ef13.png)

![image](https://user-images.githubusercontent.com/13591511/186017815-c49ca285-8892-4a3d-bf3d-fd4ab9c09114.png)

**Additional context**

**Comment by Abdelghani90** [comment]
I have just fixed it. please check and let me know. 
I think we need to add a configuration option for this one as well. Otherwise, data types that appear only in the dynamic mapping will be added by default
