### ISSUE TITLE
[BUG] Cannot add TOC section to "blank template" derived IG

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1529]
**Describe the bug**
When we derive an IG and pick "blank template", we can't add new sections to the TOC

**User Account**
any account

**URL**
any IG

**To Reproduce**
1. derive from an ig
2. choose the blank template
3. try to add a section

**Expected behavior**
user should be able to add sections

**Screenshots**
n/a
**Additional context**
n/a

**Comment by Abdelghani90** [comment]
You can add sections on using the plus button on the top right, it is going to add it in the end of the toc and you can then drag and drop it to the top.
