### ISSUE TITLE
[BUG] Conformance statement summary does not work

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#1579]
**Describe the bug**
Nothing comes up, tool just "hangs"

**User Account**
n/a

**URL**
n/a

**To Reproduce**
1. Go to an IG with conformance statements
2. Go to conformance statements section (summary)

**Expected behavior**
We should see the list of CS.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by Abdelghani90** [comment]
@carolinerosin do you still have this issue?

**Comment by carolinerosin** [comment]
seems fine now, I'll close the ticket
