### ISSUE TITLE
Labeling Issues

### ISSUE THREAD

**Issue by robnist** [usnistgov/hl7-igamt#380]
Segment (and probably other objects) have incorrect labels. See images for a sample. There are many issues, wrong label for object, incorrect label, etc.

![image](https://user-images.githubusercontent.com/14874904/49765962-eb27fa00-fca1-11e8-9011-cc48a7b976f6.png)

![image](https://user-images.githubusercontent.com/14874904/49766021-0eeb4000-fca2-11e8-86e2-de6eeafebc01.png)

![image](https://user-images.githubusercontent.com/14874904/49766328-f62f5a00-fca2-11e8-87f9-f6a3cd0c7179.png)

**Comment by Abdelghani90** [comment]
this an old version

**Comment by robnist** [comment]
Still not fixed, Harold installed new version.

![image](https://user-images.githubusercontent.com/14874904/49819282-039c2100-fd43-11e8-8e10-10c72f3a38d5.png)
