### ISSUE TITLE
Extension 4 characters requirement is annoying

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#502]
I suspect it is a requirement from Rob, but let's discuss that on a meeting. I'd like to call my flavors "MSH_ELR", "HD_ELR" etc but I can't.

**Comment by Abdelghani90** [comment]
I can change that easily when we decide

**Comment by smartinez290** [comment]
Agree! The user will need more guidance on creating this extension. Is this extension follows a specification given by Rob?

**Comment by carolinerosin** [comment]
Should be up to 4 characters (1 to 4).

**Comment by smartinez290** [comment]
@Abdelghani90 I just noticed that I can change the extension in the metadata with no issue. This is inconsistent with the 4 char requirement when creating the flavor.
