### ISSUE TITLE
Choice of occurrence is not always available where it should be

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#534]
There should be a choice of occurrence for elements that can repeat. Here's what I would like to do: 
MSH.21.3 (Universal ID) of an occurrence of MSH.21 (Message Profile Identifier) SHALL contain the value " 2.16.840.1.113883.9.11"

![image](https://user-images.githubusercontent.com/13591511/65175698-5c5ebf80-da21-11e9-9820-ea32cbe6dad4.png)

**Comment by carolinerosin** [comment]
Or if the choice is set to a default value, there should be an indication in the Description.

**Comment by HossamT** [comment]
Per Monday's update meeting it has been decided that Occurrence Number can be specified for a field from the level of a component or a subcomponent
