### ISSUE TITLE
Export to XML fails

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#536]
I'm getting the dreaded error message:
{"status":"FAILED","type":null,"text":null,"resourceId":null,"hide":false,"date":null,"data":null}

so I'm can't tell what is wrong with my IG :(

**Comment by carolinerosin** [comment]
looks like it is one of the conformance statements that causes the issue, I removed them all and was able to export

**Comment by Abdelghani90** [comment]
@Jungyubw Please check with the latest develop and the latest data

**Comment by Abdelghani90** [comment]
@Jungyubw any updates on this one ?

**Comment by Jungyubw** [comment]
It is same issue #778. I will look at it.

**Comment by Abdelghani90** [comment]
duplicated
