### ISSUE TITLE
Can't build CS:  SHALL be valued sequentially starting with the value "1" 

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#541]
Unable to build this CS: The Value of OBX-1 (Set ID-OBX) SHALL be valued sequentially starting with the value "1" within a message or for each group.

**Comment by smartinez290** [comment]
Can't build this one also:
The value of IN1-29.1 (Time) SHALL be formatted with YYYYMMDD.

**Comment by smartinez290** [comment]
Cant build this one also:
If RXA-4.1 (Time) is valued, then RXA.4.1 (Time) SHALL be identical to the RXA-3.1 (Time).

**Comment by carolinerosin** [comment]
> Can't build this one also:
> The value of IN1-29.1 (Time) SHALL be formatted with YYYYMMDD.

I've added that one in a ticket about format checking. Also I noticed this is not correctly implemented in old IGAMT as well, so we'll have to work a little bit on the date formats.

For the sequence id, I think this is one that should be part of a "pre-defined" section - we need to discuss with Rob

**Comment by smartinez290** [comment]
I can't build this one:
If RXA-20 (Completion Status) is valued and the value of RXA-20 (Completion Status) is one of List Values: 'CP','PA' then the value of RXA-9.1 (Identifier) **SHALL be one of codes listed** in the Value Set: NIP001.

**Comment by smartinez290** [comment]
I cant build this one:
The value of EI.4 (Universal ID Type) SHALL be 'ISO'.

**Comment by HossamT** [comment]
Both : 
**EI.4 (Universal ID Type) shall contain the value 'ISO'.
If RXA-4.1 (Time) is valued then RXA-4.1 (Time) shall be identical to RXA-3.1 (Time)**

 Are possible, the one with sequence id was removed until further discussion on where it applies, value set constraint was removed from the specification by Rob please discuss with Rob if you think it should be added, same for other CS formats please refer to issue #520 for CS formats

**Comment by smartinez290** [comment]
@HossamT are you still planning to add a construct to support this CS: If RXA-4.1 (Time) is valued then RXA-4.1 (Time) shall be identical to RXA-3.1 (Time)?

**Comment by smartinez290** [comment]
@HossamT I am planning to close this issue and open one for "Unable to build this CS: The Value of OBX-1 (Set ID-OBX) SHALL be valued sequentially starting with the value "1" 

It seems to me that all the other CS are supported.
