### ISSUE TITLE
Add Conformance Profile 

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#544]
I was not able to ass a Conformance Profile. Entered all the info, clicked save, but the Conformance Profile is not added in the IG. 
Also,
Adding the Name a little awkward

![image](https://user-images.githubusercontent.com/14842422/65251023-93d27800-dac4-11e9-89fb-273774573379.png)

**Comment by Abdelghani90** [comment]
For the name, this is something we decided to do in the new IGAMT, the name is the unique identifier in the IG for a conformance profile. 
Please confirm that you are not able to add the profile because I am not able to reproduce the issue.

**Comment by smartinez290** [comment]
The issue is not the name, is just that the box is too small, I can't see what I am typing when the name is long.

The Conformance Profile I can add is the ACK. It looks like the other one are ok.

**Comment by Abdelghani90** [comment]
@smartinez290 I managed to them all. check again please
