### ISSUE TITLE
Complex Conformance Statement  Question

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#555]
Why Proposition_3 and not Propositio_2? just an observation.

![image](https://user-images.githubusercontent.com/14842422/65334512-84b8fc00-db90-11e9-9ec5-45f4307136bf.png)

**Comment by HossamT** [comment]
When you create the complex pattern they are numbered in the order by which they were created in the view, first, you added the IF-THEN so you had PROPOSITION_1 and DECLARATION_2, then you added the OR so it added a PROPOSITION_3
