### ISSUE TITLE
Navigate to to Data Type Flavor

### ISSUE THREAD

**Issue by robnist** [usnistgov/hl7-igamt#570]
After creating a data type flavor or any flavor (segment, etc.) the UI should automatically navigate to flavor.

**Comment by carolinerosin** [comment]
This is something I discussed with Sandra as well. Actually I found it nice to stay on a segment I am working on, even if I added a datatype flavor. I guess it's just a matter of preference.

For example if I'm working on a PID_01 flavor, I noticed that I need a datatype flavor that I haven't created yet, I think it's nice to be able to create the flavor, but stay on the segment to finish what I'm doing. Then go to the datatype flavor later.

**Comment by ncrouzier-nist** [comment]
Both options are valid depending on what you are working on.
I would suggest adding a checkbox just under the flavor name textfield toggling the redirection to the created flavor after creation. 

![image](https://user-images.githubusercontent.com/14352180/65624623-465c7c00-df98-11e9-9e79-f2baf3d998ef.png)

**Comment by robnist** [comment]
OK. I'd say that in most cases though the user actually wants to create the flavor. I personally would not do what you are doing because I'd forget! :<)

Make the default to navigate to the flavor automatically.
