### ISSUE TITLE
Conformance Profile Flavor

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#574]
Created  a Conformance Profile flavor. Everything was going well, until I click on "Metadata" and "Cross Reference" on the created Conformance Profile  flavor. The following screen displays:

![image](https://user-images.githubusercontent.com/14842422/65783608-21921100-e11e-11e9-86ca-ef5e139897b9.png)

**Comment by smartinez290** [comment]
@Abdelghani90 I am now able to see the metadata, but not distinction is made when I create the flavor. The extension is not added.

**Comment by smartinez290** [comment]
![image](https://user-images.githubusercontent.com/14842422/66600316-456c4280-eb73-11e9-9d67-72d8a7eff7d9.png)

**Comment by Abdelghani90** [comment]
@smartinez290 I will close this one and create another one related to the naming problem
