### ISSUE TITLE
Element usage is not in sync between definition and predicate view

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#587]
I changed the usage of some components in a datatype (from O to RE)
![image](https://user-images.githubusercontent.com/13591511/66596169-65e3cf00-eb6a-11e9-86c0-224e184db1c2.png)
Then I want to set the predicate for component 10. I select "simple". When I open the "target node location" tree, the usage of the elements does not reflect what I previously set.
![image](https://user-images.githubusercontent.com/13591511/66596326-af341e80-eb6a-11e9-8235-ca9aa2ed79ac.png)

**Comment by carolinerosin** [comment]
If I hit "save" it is updated and correct in the predicate "target node location" box

**Comment by HossamT** [comment]
![bug_feature](https://user-images.githubusercontent.com/6012297/66662691-4a82cd80-ec17-11e9-8c72-23e8c16612cf.jpg)

**Comment by HossamT** [comment]
I'll hide the usage in the tree
