### ISSUE TITLE
Export binding table

### ISSUE THREAD

**Issue by Abdelghani90** [usnistgov/hl7-igamt#591]

**Comment by carolinerosin** [comment]
Here are some examples
let me know if you need more guidance

https://nistgov.sharepoint.com/:w:/s/HL7v2ConfMeth/EQFObsts53xAiSSgdTw3SdABZyKOdCD58L7FsWghveh_Ag?e=GXc7PE

**Comment by YoussefBouij** [comment]
Thank you Caroline. Are segments and datatypes the only ones concerned by binding tables ?

Regards,
Youssef
