### ISSUE TITLE
IG Clone and VS binding

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#651]
The cloned IG is not showing a V/S binding I created in a PID-10

![image](https://user-images.githubusercontent.com/14842422/67097359-f2544a00-f187-11e9-8327-3fcab71e89c7.png)

**Comment by smartinez290** [comment]
![image](https://user-images.githubusercontent.com/14842422/67097529-4b23e280-f188-11e9-86fa-3496fffc4114.png)

**Comment by smartinez290** [comment]
Also, in the Cloned IG, the binding is not showing in the PID flavor and I can't add a binding.

![image](https://user-images.githubusercontent.com/14842422/67097886-13696a80-f189-11e9-9f80-3afb11b0984a.png)

**Comment by Abdelghani90** [comment]
@Sandra,  can you use a different IG and try to reproduce it. If you started from an old one, it may be a data issue.

**Comment by smartinez290** [comment]
@Abdelghani90 it  is still happening. I just created a new IG added the binding and clone it, same behaviour.

**Comment by smartinez290** [comment]
@Abdelghani90  when I try to add a binding anywhere in the cloned IG the system hangs.

**Comment by Abdelghani90** [comment]
which value set do you have in the original IG?

**Comment by smartinez290** [comment]
I created a new value set CDCREC_IZ

**Comment by Abdelghani90** [comment]
was it a flavor of an existing or a value set created from scratch? do you see the value set in your IG?

**Comment by smartinez290** [comment]
A value set created from scratch. I can see the value set in the IG.
