### ISSUE TITLE
Missing binding in the DB

### ISSUE THREAD

**Issue by Abdelghani90** [usnistgov/hl7-igamt#676]

**Comment by carolinerosin** [comment]
Here is my analysis
[spreasdsheet](https://nistgov.sharepoint.com/:x:/s/HL7v2ConfMeth/EaFrQXeTp8dHvWQrtkG3KAcBM7waMYpIa3CHNL-CBb6HAQ?e=ImbjdG)

**Comment by carolinerosin** [comment]
So after reviewing the list, looks like not all the missing bindings refer to an HL7Table that should be present in more that one binding for a segment. That means you cannot always get the table identifier from your segment object

**Comment by Abdelghani90** [comment]
@carolinerosin we need to check again with the new Data.
