### ISSUE TITLE
Differential Mode Export

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#687]
While in Differential Mode:
1. Clicked "Export"
2. Selected "Updated" and "Added"
3. Clicked "Submit"
The following error displays:

![image](https://user-images.githubusercontent.com/14842422/67973853-affb2600-fbe7-11e9-8cde-1c9ddd9043f6.png)

**Comment by Abdelghani90** [comment]
@smartinez290 any updates?
