### ISSUE TITLE
PHINVADS value set - AS Flavor with no codes

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#699]
Is this part of the specfication? The URL have to be entered by the user? This type of value set, based on the spec is consider external. 
![image](https://user-images.githubusercontent.com/14842422/68686599-dd29cb80-0539-11ea-82a0-6caa703c6566.png)

Here is the spec I am referring (the last row)
![image](https://user-images.githubusercontent.com/14842422/68686669-fa5e9a00-0539-11ea-816e-187df3fd048b.png)

Also, I notice the Metadata is not including the type (Internal or External)

**Comment by Abdelghani90** [comment]
@smartinez290 I will review this once we have the Vocabulary service.
