### ISSUE TITLE
Clone IG Conformance Statement ID

### ISSUE THREAD

**Issue by HossamT** [usnistgov/hl7-igamt#700]
When cloning an IG, the reference to the Conformance Statement do not change, changing a conformance statement from the Original or Clone, changes the values in all the IGs

**Comment by Abdelghani90** [comment]
@Jungyubw  I still have the issue

**Comment by Jungyubw** [comment]
@Abdelghani90 I am working on now...

**Comment by Jungyubw** [comment]
fixed. Sorry for too late...
