### ISSUE TITLE
Can't rearrange the order of messages in the new IGAMT

### ISSUE THREAD

**Issue by csnewman88** [usnistgov/hl7-igamt#733]
In the new IGAMT, I can't seem to rearrange the order of the messages. It looks like it's alphabetical now (ACK before ORU) but given the flow of messages it would make more sense to define the ORU first. I've tried to drag and drop the ORU section in the table of contents (like you can do for the narrative portions of the IG) but it doesn't seem to work.

**Comment by Abdelghani90** [comment]
It is fixed.
