### ISSUE TITLE
Deleting Co-constraint Groups - system hangs

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#737]
I have imported this group in a co-constraint table. If I have to delete it first, a message should be alerting the user.

**Comment by smartinez290** [comment]
@HossamT just deleted the co-constraint table that have the group in it. Tried to delete the CCG and still hangs. 

It looks like deleting a CCG is not working,

**Comment by HossamT** [comment]
We need to do cross-references for CoConstraint Groups before allowing the delete, @Abdelghani90 will do the cross-references and I'll do the delete when it's done.
