### ISSUE TITLE
Table 0396

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#742]
Per Rob:
These are supposed to be clean. The tables project I believe solved these issues. 
Caroline, what is the status of using this codes?
![image](https://user-images.githubusercontent.com/14842422/72074157-5f770780-32bf-11ea-9361-8f290b547959.png)

**Comment by carolinerosin** [comment]
I haven't have time to look more into the tables projects yet. I think this issue is coming from Frank's db because this where we extract the data from (for the moment)

**Comment by Abdelghani90** [comment]
duplicated
