### ISSUE TITLE
Segment Data QA 2.8.1 - Findings

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#749]
![image](https://user-images.githubusercontent.com/14842422/72185434-c4665680-33c0-11ea-8c48-8af760974f8a.png)

**Comment by robnist** [comment]
Are you saying there is a C.LEN associated at the segment level and it is missing? Segments should have no length information.

I'm not sure how to read the image.

**Comment by smartinez290** [comment]
I am comparing the Spec with what is in IGAMT. When I say IGAMT missing C-Len I mean that the spec has a C-Len only and is not showing in IGAMT.
See MSH-8 for example in the Spec

![image](https://user-images.githubusercontent.com/14842422/72186532-7e5ec200-33c3-11ea-9210-9efe2757e991.png)

This is how it shows in IGAMT -- It might be ok, but I am just comparing the two.

![image](https://user-images.githubusercontent.com/14842422/72186685-caaa0200-33c3-11ea-875e-e1abb0a89dc5.png)

**Comment by smartinez290** [comment]
I am referring to the fields in the segment.
