### ISSUE TITLE
2.7 QA Findings on Message Structure

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#750]
![image](https://user-images.githubusercontent.com/14842422/72362461-3987a380-36c1-11ea-9e51-3e94192f5798.png)

**Comment by smartinez290** [comment]
![image](https://user-images.githubusercontent.com/14842422/72362546-5cb25300-36c1-11ea-81d1-744e123fd100.png)

![image](https://user-images.githubusercontent.com/14842422/72362565-5fad4380-36c1-11ea-9728-0860e75c5ad2.png)

**Comment by Abdelghani90** [comment]
@smartinez290 @carolinerosin is this fixed in the latest data ?

**Comment by carolinerosin** [comment]
I don't think this is a data issue, it is more of a standard issue. I'm not sure how to fix that. We'll need to talk with Rob I think
