### ISSUE TITLE
2.7.1 QA Data findings

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#751]
The following data structure are missing in 2.7.1

QBP^Q11^Q11_Q11
RSP^K11^RSP_K11
VXU^V04^VXU_V04
ORA^R33
OUL^R22,R23,24
OPU^R25

**Comment by Abdelghani90** [comment]
@carolinerosin @smartinez290 is it fixed in the latest data ?

**Comment by carolinerosin** [comment]
Looks like this is fixed yes. @smartinez290 can you double check as well ?

**Comment by smartinez290** [comment]
@carolinerosin it looks like is fixed!
