### ISSUE TITLE
Value set flavor extension

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#770]
Why the value set is showing in the extension and indicating that is the extension is duplicated? I just wanted to add the extension.

![image](https://user-images.githubusercontent.com/14842422/73087103-f804ae80-3e9f-11ea-81f0-1ccf365fd121.png)

**Comment by smartinez290** [comment]
![image](https://user-images.githubusercontent.com/14842422/73087249-3e5a0d80-3ea0-11ea-97a9-68836a17b61e.png)

**Comment by Abdelghani90** [comment]
Because we start with the extension of the original object.

**Comment by Abdelghani90** [comment]
fixed
