### ISSUE TITLE
Co-Constraint Table

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#775]
Added another Co-CoConstraint Table Binding and to this one I added another column OBX-6.1. The Drop down under IBX-3 is not working. It was working in the table above.

![image](https://user-images.githubusercontent.com/14842422/73105602-7b85c600-3ec7-11ea-9c55-eea6cc40bca3.png)

**Comment by HossamT** [comment]
**Solution** :
Same for #799 this will be closed as duplicate
