### ISSUE TITLE
Export Conformance Predicates missing

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#779]
In addition of missing Conformance Predicates, the conditional  is not spelled correctly

![image](https://user-images.githubusercontent.com/14842422/73216516-22669e00-4124-11ea-9b3f-2057de6be52d.png)

**Comment by smartinez290** [comment]
Conformance Predicates are there. Just need to change CAB usage to C(A/B))

**Comment by Abdelghani90** [comment]
@YoussefBouij did you fixed this one ?
