### ISSUE TITLE
Export - DT Flavor not exported when only used in a co-constraint table

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#780]
If used the DT flavor, CE_IZ,  in the co-constraint table only the DT flavor is not exported.
When I use the DT flavor in an Segment it is exported. 

![image](https://user-images.githubusercontent.com/14842422/73216955-07485e00-4125-11ea-9723-b4edbc84ba7a.png)

**Comment by smartinez290** [comment]
Just to clarify ... I created a DT flavor, but only used it in the co-constraint table, not in any other element. In the Export, the DT flavor is no listed under data type in TOC. 

I am also using a User Export Configuration to include everything (optional and excluded elements)

**Comment by Abdelghani90** [comment]
@YoussefBouij We need to check if a datatype or a value set is used inside the one of the exported co-constraints. For now, we are only checking fields and components based on the usages
