### ISSUE TITLE
Creating Segment Flavors

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#787]
This was working before,

I created a flavor with extension _IZ, but only the I is showing. Also the tool is allowing the creation of a duplicate flavor.

![image](https://user-images.githubusercontent.com/14842422/73940957-62631900-48ba-11ea-81a5-a338b70c925e.png)
![image](https://user-images.githubusercontent.com/14842422/73941193-c7b70a00-48ba-11ea-9bd5-5d5562bbc51e.png)

**Comment by Abdelghani90** [comment]
Hi @smartinez290,

I found the Issue and fixed it. I will include it in the next deployment.

**Comment by smartinez290** [comment]
@Jungyubw is also happening in the value sets. Also, I can only enter one character in the extension:

![image](https://user-images.githubusercontent.com/14842422/73950166-706c6600-48c9-11ea-9b5b-5eab48472ab6.png)
