### ISSUE TITLE
Select Tool Scope

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#791]
The drop down is not obvious - recommend making the title bold, like in old IGAMT. 
"Select Tool Scope" instead of "select tool scopes"
Also, 
"Export to GVT" instead of "Export GVT"

Why are we  not allow to create a Tools Scope and only select? 

Was this an implementation decision from Rob?

**Comment by Abdelghani90** [comment]
I will fix it ASAP.

**Comment by smartinez290** [comment]
@Abdelghani90 this issue is still active

**Comment by ncrouzier-nist** [comment]
Reopening this issue as the text has not changed AND the user can proceed without having chosen a tools scope which will end up in an error in GVT.

Make tool scope selection mandatory (and pop up more)
