### ISSUE TITLE
Export: HTML-Quick

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#792]
I am getting an error when this option is selected prior to any customization.  It looks like I have to  customized in order for this option to work. 

{"status":"FAILED","type":null,"text":"Error while sending back exported IG Document with id 5e417b139194be0006bf79c1\nnull","resourceId":null,"hide":false,"date":null,"data":null}

**Comment by Abdelghani90** [comment]
@YoussefBouij the "quick mode" doesn't work when we export an IG for the first time. In the case of the first export, you could either export with the default configuration or not show the button of the quick export.
