### ISSUE TITLE
Export: Post-Definition in wrong location and not exported for V/S

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#794]
For segment is in the wrong location. It should be at the end after the segment definition.
For V/S Pre-Definition and Post-Definition are not exported at all.

**Comment by Abdelghani90** [comment]
We need to check if we have the same order that we have in the old IGAMT for all the exported elements.

**Comment by Abdelghani90** [comment]
@smartinez290 They are exported if you include them in the configuration.
@YoussefBouij Post definition should be always the last thing to export.( for segments for example it is exported before the binding table)
