### ISSUE TITLE
Co-constraints - binding location using "code"

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#795]
It was not obvious that I needed to select a binding location. I noticed that location was empty in the export.  Highlighting the drop down in red will help. 
![image](https://user-images.githubusercontent.com/14842422/74243169-404c0b00-4cad-11ea-9110-52a13c1d7a9e.png)

**Comment by HossamT** [comment]
**Solution** : 
Highlight the Binding Location Dropdown in red when missing
