### ISSUE TITLE
Co-constraints - Condition

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#796]
I can't drag and drop IF-Then when adding a condition to a co-constraint table 

![image](https://user-images.githubusercontent.com/14842422/74246005-dd10a780-4cb1-11ea-8ce0-bd0c99e664da.png)

**Comment by HossamT** [comment]
**Solution** : 
Remove the IF-THEN from the possible operators when creation a proposition (The IF-THEN is implied)
