### ISSUE TITLE
Co-constraint Group

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#798]
Got this error after creation of a Co-constraint Group:

![image](https://user-images.githubusercontent.com/14842422/74267547-43a6bd00-4cd4-11ea-9e57-f339e670efcf.png)

**Comment by Abdelghani90** [comment]
@smartinez290 Please give more details. the screenshot does not show the error you have I guess

**Comment by Abdelghani90** [comment]
@smartinez290 any update on this ?

**Comment by smartinez290** [comment]
@Abdelghani90 I will take a look

**Comment by smartinez290** [comment]
@Abdelghani90 I can't tested -- not able to create a co-constraint group. 

![image](https://user-images.githubusercontent.com/14842422/79236028-61121780-7e3a-11ea-962b-1ebc3713c8af.png)

**Comment by smartinez290** [comment]
@Abdelghani90 what is this Co-Constraint Group false?? I click on it nothing happened.
