### ISSUE TITLE
Export: Derived Profile/Differential View

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#801]
Configured a User Export Configuration where all the options were selected (to export everything)

The Exported document successfully shows updated elements in at message content.
Notice that the OBX_TX is not listed under the Data Types. This segment was added in the derived profile. 

![image](https://user-images.githubusercontent.com/14842422/74371063-26daba00-4da6-11ea-8f0e-083e169b6a6b.png)

The OBR segment was deleted, I guess this is why this one is not here. It is highlighted in orange to indicate that it was updated, but I have no idea of what the update was.

**Comment by smartinez290** [comment]
Also all DT flavors are missing from the Derived IG export

**Comment by Abdelghani90** [comment]
You have to select them if they were not checked by default
