### ISSUE TITLE
IG Tab option for Publish and Derive from

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#806]
Not having a color for the Publish and Derive from tab is confusing for the user. I suggest using a tab with another color. S I am always tempted to click Open thinking that I am selecting Publish or Derive from.

![image](https://user-images.githubusercontent.com/14842422/74863948-b9d2a180-531c-11ea-9385-6b049b98ec6d.png)
![image](https://user-images.githubusercontent.com/14842422/74863975-c7882700-531c-11ea-9264-77d08b817751.png)

**Comment by Abdelghani90** [comment]
I guess the dialogue will prevent you now. I will close it for now
