### ISSUE TITLE
Conformance statements UI issue + unable to save

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#821]
1. I created a flavor of EIP datatype (EIP_ELR)
![image](https://user-images.githubusercontent.com/13591511/75694068-f041e200-5c75-11ea-963d-6e819110327b.png)

2. I set the usage of EIP_ELR.2 to R and changed the datatype flavor to EI_ELR (this is another flavor I created)
![image](https://user-images.githubusercontent.com/13591511/75693346-cd62fe00-5c74-11ea-81ff-7a6c07d92ef8.png)

3. I go to "conformance statements" and I only see _List of conformance statements_ (instead of _List of conformance statements_, _Available Conformance Statements_ and _Associated datatypes conformance statements_)
![image](https://user-images.githubusercontent.com/13591511/75693474-fa171580-5c74-11ea-88a2-dfb5ab9a71b0.png)

4. I create a simple conformance statement
![image](https://user-images.githubusercontent.com/13591511/75693575-203cb580-5c75-11ea-989a-fcd68cd26036.png)

![image](https://user-images.githubusercontent.com/13591511/75693603-2c287780-5c75-11ea-976e-ccb25614627e.png)

The save button is not enabled, so I cannot save what I entered.
If I go somewhere else (example go to Metadata) and come back to Conformance statements, my conformance statement is gone (since I was not able to save it)

I noticed this issue when I changed the datatype of my EIP_ELR.2 to EI_ELR. If I leave the original datatype (EI from standard), I don't have the issue, I can save my conformance statement.

**Comment by HossamT** [comment]
@carolinerosin I checked this issue but I could not trigger it, can you double-check? It might be fixed
