### ISSUE TITLE
Predicate builder should allow to select a complex element to be select for is/ is not valued

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-igamt#823]
I'm trying to use IGAMT-2 to re-create an IG that I have in old IGAMT. I have a few predicates in old-IGAMT that I cannot create in IGAMT-2. I think the predicate builder should allow to choose a complex element for the "is valued" and "is not valued" content declarative statement.

This is what I have in old IGAMT
![image](https://user-images.githubusercontent.com/13591511/75710531-bdf2ad80-5c92-11ea-987d-e47f8e9c3b8b.png)

In IGAMT-2 I cannot select NK1-13 (because only primitive element are selectable)

**Comment by HossamT** [comment]
**Solution** :
Allow Complex Elements to be selected in the Predicate Builder and filter Declarative Statement to valued and not valued
