### ISSUE TITLE
Export - not exporting segment flavor

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#835]
Created a segment flavor and used it in the conformance profile -- it is also Required. Is not showing in the export. PID_IZ

![image](https://user-images.githubusercontent.com/14842422/76350284-dc375980-62e1-11ea-99b9-a1ead108facd.png)

**Comment by smartinez290** [comment]
also the "RE" CE_IZ dt flavor used in the PID_IZ segment is not in the export.

**Comment by Abdelghani90** [comment]
Did you save before you export ?

**Comment by smartinez290** [comment]
@Abdelghani90 I believe I did. I just exported again this morning and now I see them. I will let you know if it happens again. For now I will close this issue.
