### ISSUE TITLE
Can't create CS

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#836]
I cant create this CS: RXA-9.1 (Identifier) SHALL NOT be valued  -- 

Not listed in the declaration:

![image](https://user-images.githubusercontent.com/14842422/76353959-03912500-62e8-11ea-8800-54fb92f33220.png)

**Comment by robnist** [comment]
Nor should you. Mark the usage as 'X'. 

DO NOT use CS where other conformance constructs exists.

Any changes to the CS and CP language needs to go through Caroline and me.

This goes for any requirement, use the Conformance document as requirements....

**Comment by smartinez290** [comment]
@robnist I was trying to create this complex CS from the CDC IG:
If RXA-20 (Completion Status) is not valued or the value of RXA-20 (Completion Status) is not one of List Values: 'CP','PA' then RXA-9.1 (Identifier) SHALL NOT be valued.

and the last declaration is not there.

**Comment by smartinez290** [comment]
@robnist I just cut and pasted the last part... but the issue is that I can create that complex CS

**Comment by robnist** [comment]
We need to look at this then. Probably will need to add "SHALL NOT" contain a value, and only for the declarative part of the CP.

Assign to me and Caroline.

**Comment by smartinez290** [comment]
@robnist @carolinerosin can't create this one either:

If RXA-20 (Completion Status) is valued and the value of RXA-20 (Completion Status) is one of List Values: 'CP','PA' then the value of RXA-9.1 (Identifier) SHALL be one of codes listed in the Value Set: NIP001.

**Comment by carolinerosin** [comment]
_If RXA-20 (Completion Status) is not valued or the value of RXA-20 (Completion Status) is not one of List Values: 'CP','PA' then RXA-9.1 (Identifier) SHALL NOT be valued._

Shouldn't that be constructed as a condition predicate ? A C(.../X) usage with the predicate "If RXA-20 (Completion Status) is not valued or the value of RXA-20 (Completion Status) is not one of List Values: 'CP','PA'" ? @robnist @smartinez290 

For the second one, we'll have to double check first how we want that to be handled. Looks a little bit like a co-constraint to me, but not quit the same as the OBX ones ? I'm going to discuss with @HossamT to see what the best way to handle that is. I was thinking about been able to create conditional value set bindings - maybe that would be the cleanest solution, but it would need to be implemented in the validation first.

**Comment by HossamT** [comment]
@carolinerosin from all the discussion we had, should this be closed?

**Comment by carolinerosin** [comment]
yep I think we can close it
