### ISSUE TITLE
Complex Conditional Predicate

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#837]
It looks like the UI to create a Complex CP is not working... I can't drag and drop the if/then

![image](https://user-images.githubusercontent.com/14842422/76360829-288b9500-62f4-11ea-9e2d-e7cff186afe3.png)

**Comment by HossamT** [comment]
Solution :
Remove the IF-THEN from the possible operators when creation a proposition (The IF-THEN is implied)

Same as #796

**Comment by smartinez290** [comment]
@HossamT should I leave this ticket open? I was able to create the CP, but l guess your are planning to remove the IF-THEN.

**Comment by HossamT** [comment]
I already did, but it's not deployed yet, just leave it open for now so that you can QA that it has been removed after deployment
