### ISSUE TITLE
Single Code

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#839]
Added a single code binding to MSH-15  At Message Level 

Exported IG:
MSH-15 is not listed in the Export under Value Set Binding, but MSH-16  is listed twice:

![image](https://user-images.githubusercontent.com/14842422/76428859-9ed7d800-6384-11ea-9f72-9c16cefc48eb.png)

![image](https://user-images.githubusercontent.com/14842422/76429095-f0806280-6384-11ea-88c0-6df7a57d53c4.png)

**Comment by smartinez290** [comment]
@Abdelghani90 Also, MSH-15 and 16 are Required and they are not showing up in the Segment Definition Table.

**Comment by smartinez290** [comment]
@Abdelghani90 also added a single value in the PID-8 -- the export does not display the single binding at all. 

![image](https://user-images.githubusercontent.com/14842422/76430280-8668bd00-6386-11ea-883d-5b7beb1fa044.png)

**Comment by smartinez290** [comment]
@YoussefBouij @Abdelghani90 single binding are still not exported.
Also, noticed the binding in PID-8 and PID-10
![image](https://user-images.githubusercontent.com/14842422/79228651-cdd3e480-7e2f-11ea-9c7e-16a28833ebd4.png)
Notice the inconsitency in the export -- PID-8 shows no binding at all and PID-10 is showing the binding to the value set instead of the single binding. 
![image](https://user-images.githubusercontent.com/14842422/79228833-18556100-7e30-11ea-92ec-77d4c508817f.png)

**Comment by smartinez290** [comment]
@Abdelghani90 @YoussefBouij was this issue fixed? for next deployment?

**Comment by Abdelghani90** [comment]
Yes it will be included in the next deployment
