### ISSUE TITLE
Profile Viewer - GVT

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#842]
Notice that the CE DT can't be expanded, but the CE_IZ is ok.

![image](https://user-images.githubusercontent.com/14842422/76626102-e9855b80-650e-11ea-8ad4-0ae5c475c44d.png)

**Comment by HossamT** [comment]
I can't know what's happening here without looking at XML, may be @ncrouzier-nist has an idea

**Comment by smartinez290** [comment]
@HossamT I am closing this one for now. I just check and now I am able to expand the base DT.
