### ISSUE TITLE
CS not displayed in profile viewer and not validation

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#843]
Created these two CS -- They do not appear in the Profile viewer, probably not in the XML because validation is not generating errors on these CSs.

![image](https://user-images.githubusercontent.com/14842422/76633575-530b6700-651b-11ea-816f-9153793e0a86.png)

Here are the CS in Profile viewer, only the simple CS I created is displayed, the other two are not. 

![image](https://user-images.githubusercontent.com/14842422/76633668-76361680-651b-11ea-8339-d162911a7cbd.png)

**Comment by HossamT** [comment]
Need to see XML to know if it's a validation or export issue

**Comment by smartinez290** [comment]
[NIST-IGAMT-Profiling-Guide-5e62985a08bb3a000648c146_20200316_182421.zip](https://github.com/usnistgov/hl7-igamt/files/4339796/NIST-IGAMT-Profiling-Guide-5e62985a08bb3a000648c146_20200316_182421.zip)

**Comment by HossamT** [comment]
Your conformance statements are defined on RXA_IZ, but the message uses RXA
