### ISSUE TITLE
Validation: Format 

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#845]
Wondering... Is this the expected validation? Generating two format errors:
MSH|^~\&|Test I Application|X68||NIST Test Iz Reg|Date||VXU^V04^VXU_V04|20120814^H|P|2.5.1|||ER|AL|||||Z22^CDCPHINVS

![image](https://user-images.githubusercontent.com/14842422/76768840-fbb30400-6771-11ea-8eca-24b2877049b6.png)

**Comment by HossamT** [comment]
- The first Error is triggered by the format validation, it's the generic format for all DTMs in the standard.
- The second Error is triggered by the additional constraint created in IGAMT for a DTM, it so happens that in this case both the standard format and the additional one are the same.

@carolinerosin does this seem like the behavior we're looking for?

**Comment by carolinerosin** [comment]
yes that's normal.
In the future we can implement a new type of constraint, specific to DTM to avoid using regex.

So as of now - this is correct and is the intended behavior.
