### ISSUE TITLE
Allow users to see documentation tab without login

### ISSUE THREAD

**Issue by Abdelghani90** [usnistgov/hl7-igamt#846]

**Comment by smartinez290** [comment]
@Abdelghani90 It looks like now a user that is not logged on can access the Documentation, but the slides are not visible 

![image](https://user-images.githubusercontent.com/14842422/77318803-16422b80-6ce4-11ea-947e-084ae7bb8732.png)

**Comment by Abdelghani90** [comment]
Fixed I will deploy it soon.
