### ISSUE TITLE
Validation: ISO-compliant OID error not generated

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#848]
[NIST-IGAMT-Profiling-Guide-5e62985a08bb3a000648c146_20200317_151745.zip](https://github.com/usnistgov/hl7-igamt/files/4344199/NIST-IGAMT-Profiling-Guide-5e62985a08bb3a000648c146_20200317_151745.zip)

used this message:

MSH|^~\&|Test I Application|X68||NIST Test Iz Reg|20120701082240-0500||VXU^V04^VXU_V04|NIST-IZ-001.00|P|2.5.1|||ER|AL|||||Z22^CDCPHINVS^A^F
PID|1||D26376273^^^NIST MPI^MR||Snow^Madelynn^Ainsley^^^^L|Lam^Morgan^^^^^M|20070706|F||2135-2^Native Hawaiian or Other Pacific Islander^CDCREC|32 Prescott Street Ave^^Warwick^MA^02452^USA^L||^PRN^PH^^^657^5558563|||||||||H^non Hispanic or Latino^HL70189
PD1|||||||||||02^Reminder/Recall - any method^HL70215|||||A|20120701|20120701
NK1|1|Lam^Morgan^^^^^L|MTH^Mother^HL70063|32 Prescott Street Ave^^Warwick^MA^02452^USA^L|^PRN^PH^^^657^5558563
ORC|RE||IZ-783274^NDA|||||||I-23432^Burden^Donna^A^^^^^NIST-AA-1^^^^PRN||57422^RADON^NICHOLAS^^^^^^NIST-AA-1^L^^^MD
RXA|0|1|20120814|20120814|15^Influenza, seasonal, injectable, preservative free^HL70292|0.5|mL^MilliLiter [SI Volume Units]^UCUM||00^New immunization record^NIP001|7832-1^Lemon^Mike^A^^^^^NIST-AA-1^^^^PRN|^^^X68||||Z0860BB|20121104|CSL^CSL Behring^MVX|||CP|A
RXR|IM^Intramuscular^HL70162|LD^Left Arm^HL70163
OBX|1|CE|64994-7^Vaccine funding program eligibility category^LN|1|V05^VFC eligible - Federally Qualified Health Center Patient (under-insured)^HL70064||||||F|||20120701|||VXC40^Eligibility captured at the immunization level^CDCPHINVS

**Comment by HossamT** [comment]
@Jungyubw same as the answer for #847

**Comment by Jungyubw** [comment]
fixed
