### ISSUE TITLE
Documentation Tab - UG

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#849]
Any way to make the UG ToC more readable? 
Old IGAMT:

![image](https://user-images.githubusercontent.com/14842422/76966790-e1596180-68fc-11ea-8f6c-44d102dd5821.png)

IGAMT-2

![image](https://user-images.githubusercontent.com/14842422/76966869-fdf59980-68fc-11ea-8c32-bedc14d7910b.png)

**Comment by Abdelghani90** [comment]
Sure, I will
