### ISSUE TITLE
Documentation: Adding a Section

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#853]
@Abdelghani90 In order to add a new section, I have to added as a sub-section, then drag and drop to the exact location. In other words, I am not able to right click on the root section of the TOC to add Section:

![image](https://user-images.githubusercontent.com/14842422/77332955-2284b380-6cf9-11ea-8e15-7d0d819055bb.png)

**Comment by Abdelghani90** [comment]
there is a + button that you can use to add a section at the bottom
<img width="354" alt="Screen Shot 2020-03-23 at 12 30 03 PM" src="https://user-images.githubusercontent.com/16800878/77339426-223ce600-6d02-11ea-87c4-8838a7acc7d4.png">

**Comment by smartinez290** [comment]
@Abdelghani90 that will work for me, but this means that the tool does not allow to add more than two sections before the Message Infrastructure Section?

**Comment by Abdelghani90** [comment]
you can add at the bottom and then drag and drop
