### ISSUE TITLE
Cant Create CS 

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#858]
@HossamT I am not able to create this CS because the declaration is not available "Shall be one of the codes listed in V/S.."
IZ-31: If RXA-20 (Completion Status) is valued and the value of RXA-20 (Completion Status) is one of List Values: 'CP','PA' then the value of RXA-9.1 (Identifier) **SHALL be one of codes listed in the Value Set: NIP001.**

**Comment by smartinez290** [comment]
@HossamT I just realized that I can use this declaration:
![image](https://user-images.githubusercontent.com/14842422/77542573-c5196f80-6e7c-11ea-985b-ea1842f7a099.png)

**Comment by smartinez290** [comment]
@HossamT never mind, the issue is still outstanding... in this declaration I need to enter a value.

**Comment by smartinez290** [comment]
@carolinerosin the IG is the published IG:  CDC 2.5.1 Immunization Profile Z22

**Comment by HossamT** [comment]
Closed, duplicate of #1012
