### ISSUE TITLE
Complex-CS  using EXIST not exported

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#860]
@HossamT it looks like even all CS that are using EXIST are not been exported, I just created another one where all the declarations are supported and the CS is not showing up in GVT profile viewer:

![image](https://user-images.githubusercontent.com/14842422/77581313-e6498280-6eb3-11ea-8568-960b9d512382.png)

**Comment by smartinez290** [comment]
@ncrouzier-nist same IG

**Comment by ncrouzier-nist** [comment]
See #861
