### ISSUE TITLE
CS at Message Level not included in GVT Profile Viewer

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#861]
Created the following CS at message level:
![image](https://user-images.githubusercontent.com/14842422/77654016-d464ef80-6f46-11ea-8bce-c259ff77d0b7.png)

It looks like it was exported because an error message for this CS is generated:
![image](https://user-images.githubusercontent.com/14842422/77654173-168e3100-6f47-11ea-94e6-944a5b3d5d5f.png)

But is not in the Profile Viewer:
![image](https://user-images.githubusercontent.com/14842422/77654278-3f162b00-6f47-11ea-9fc5-68f0498ed5de.png)

Not sure to who I should assign this issue.

**Comment by ncrouzier-nist** [comment]
@smartinez290 , can you send me the export from IGAMT (via n-files) for me to test.
Thanks!

**Comment by smartinez290** [comment]
just did via email

**Comment by ncrouzier-nist** [comment]
thanks

**Comment by smartinez290** [comment]
@ncrouzier-nist just did. The CS is now showing in profile viewer. Thanks.

**Comment by smartinez290** [comment]
@ncrouzier-nist I will close when is  deployed in GVT production.

**Comment by ncrouzier-nist** [comment]
Done.

**Comment by smartinez290** [comment]
@ncrouzier-nist when I push to GVT it connects but it is not taking me to the Tool Scope. This happened before and it when away....
![image](https://user-images.githubusercontent.com/14842422/78051039-20e76b00-734b-11ea-8e1c-53654fb0bd85.png)

**Comment by smartinez290** [comment]
@ncrouzier-nist it works now.... not sure why this is happening
