### ISSUE TITLE
Validation not showing right Path

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#862]
Why the constraint failure for IZ-09 is not showing the right path.

![image](https://user-images.githubusercontent.com/14842422/77655036-3bcf6f00-6f48-11ea-82f8-d34b6097cee4.png)

**Comment by smartinez290** [comment]
@Jungyubw this looks like the issue in old IGAMT, but I can't look at the assertion in the new IGAMT. 
Is this functionality is going to be available in IGAMT-2? I looked at the XML export and the assertion seem to be correct. 

Could you take a look?

**Comment by Jungyubw** [comment]
Sure I am checking now.

**Comment by Jungyubw** [comment]
@HossamT Could you look at this issue? In the XML there is no difference.

**Comment by HossamT** [comment]
@Jungyubw can you send me XML

**Comment by smartinez290** [comment]
@HossamT @Jungyubw it looks like this issue is still pending.

**Comment by Jungyubw** [comment]
You can see IZ-09 and IZ-10. Only difference is one is for Segment and other is for Message

[NIST-IGAMT-Profiling-Guide[derived]-5e821e2cb3cb1f00064369f1_20200414_154031.zip](https://github.com/usnistgov/hl7-igamt/files/4476533/NIST-IGAMT-Profiling-Guide.derived.-5e821e2cb3cb1f00064369f1_20200414_154031.zip)

**Comment by smartinez290** [comment]
@HossamT any status on this issue. Is it really an issue? I am still getting it.

**Comment by smartinez290** [comment]
@HossamT @Jungyubw this issue is still outstanding. It looks like it has not been addressed.

**Comment by Jungyubw** [comment]
@smartinez290 Do you still have this issue?
