### ISSUE TITLE
Deleted CS shows in UI

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#863]
The following CS IZ-40 was deleted in the IG, but is displayed as a CS that can be used. 

![image](https://user-images.githubusercontent.com/14842422/77764956-e3fe3a00-7013-11ea-9245-704b593415b7.png)

It does not appear in the HTML export. 
It does not appear in the XML export -- but This type of CS are not been exported (cited in a different issue)

**Comment by Jungyubw** [comment]
I will look at this.
