### ISSUE TITLE
Export Configuration - Delta ON/Off

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#864]
Tried to create a user configuration turning Delta of for segments and DT. The Delta ON/OFF button is not responding. I am only able to switch at the Message level.

**Comment by smartinez290** [comment]
@YoussefBouij related to this issue. I am able to turn the Delta button off at the message level, but when I export using the user Config. with the Delta off, the updates are highlighted.

**Comment by YoussefBouij** [comment]
Could you create a different ticket for each one ? I think theses are different issues

**Comment by smartinez290** [comment]
@YoussefBouij See issue #872  for the second issue.

**Comment by smartinez290** [comment]
@YoussefBouij I am closing this issue because @mellouli-dev removed the delta option in the Export Configuration. Delta On/Off option is now only available when customizing the export configurations in a Derived IG.
