### ISSUE TITLE
Export Word (quick) failing

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#868]
The following error is generated when trying to export in Word (quick)

![image](https://user-images.githubusercontent.com/14842422/78059916-b63d2c00-7358-11ea-846c-306fbd06c279.png)

I tried different IGs and I get the same result.

**Comment by YoussefBouij** [comment]
Do the same IGs fail or pass for HTML quick export ?

**Comment by smartinez290** [comment]
@YoussefBouij the error was generated only on Word quick.
But,  I just tested it and is working. Did you fixed it? I logged out again trying to recreate using the default config -- word quick and is working.

**Comment by smartinez290** [comment]
@YoussefBouij word and HTML quick are not working.

![image](https://user-images.githubusercontent.com/14842422/79228325-3bcbdc00-7e2f-11ea-9fbf-c117c2203c92.png)

**Comment by YoussefBouij** [comment]
Can you give more details to when this error occurs ? I'm not able to reproduce it locally.

**Comment by smartinez290** [comment]
Putting this Ticket on hold, unable to recreate.
