### ISSUE TITLE
Delta Off - not getting the same results at segment level

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#870]
@mellouli-dev Could you please take a look at the same IG we discussed today. I made updates at the Message Level GT1 usage and also at segment level in the MSH segment.

When I customize the export to turn the Delta Off at the message level and also at the segment level. 

I am getting the updated element at the message level highlighted, but the element at the segment level is not.

**Comment by smartinez290** [comment]
@YoussefBouij @YoussefBouij just tested the following:
1. Using Derived IG 
2. customized default Config
3. Selected Delta On/Hightlighted at message and also at segment level (I made updates)
4. Exported using this customized export -- The exported document is not highlighting the updates

**Comment by YoussefBouij** [comment]
Same here, when I'm following the same steps you described, it works fine for me.
Also it's weird that it's not highlighting anything at all, when it worked for you on other instances right ?
