### ISSUE TITLE
PHINVADS V/S binding - Export fails

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#915]
I can't export an IG that have a PHIINVAD binding. The following error is generated:
![image](https://user-images.githubusercontent.com/14842422/79604802-c2e1b400-80bc-11ea-809b-90deee2fd3a0.png)

**Comment by Abdelghani90** [comment]
Hi Sandra, could you give more details. For example: 
The level of the binding. 
the name of the Phinvad VS.
The version of the profile

**Comment by smartinez290** [comment]
@Abdelghani90 it looks like only creating the v/s is causing a problem... I tried again, with no binding and I was not able to connect to GVT nor export the IG.

![image](https://user-images.githubusercontent.com/14842422/81006007-d1e69700-8e1c-11ea-900d-f4c5300001bd.png)

**Comment by smartinez290** [comment]
@Abdelghani90 I just tried just adding a new value set, try to export the IG, got  the same error. I can't connect to GVT, just hanging.

**Comment by smartinez290** [comment]
@Abdelghani90 I found the issue, there was an empty row in the table that listed the codes in one of the value set. I removed the line and it exported with no issues. Consider not allowing empty rows in the the value sets.

**Comment by mellouli-dev** [comment]
@smartinez290 was the empty row in a PHINVADS valueset or just an HL7 one?

**Comment by smartinez290** [comment]
@Abdelghani90  I thought originally that it was caused by the PHINVADS, but it was in an HL7 v/s.

**Comment by smartinez290** [comment]
@Abdelghani90 @YoussefBouij @Jungyubw it is not happening when I create a new value set and leave an empty row. 
In summary, If I leave an empty row in an HL7 v/s flavor I am not able to export in HTML, but I am able to export XML. If I leave an empty row in a PHINVADS or a new value set I am not getting the error.

**Comment by smartinez290** [comment]
@Abdelghani90 @YoussefBouij @Jungyubw 
I just got the same issue. Not able to export the IG in HTML or Word. I am able to export the XML. 
Getting this error:
![image](https://user-images.githubusercontent.com/14842422/81828761-29b18c00-9508-11ea-8c87-6f3f0e5e5145.png)
The verification is showing these fatal errors, but they can't be fixed. I am not able to enter the missing Name.  I am thinking this is the issue, but why I am able to export the XML?
![image](https://user-images.githubusercontent.com/14842422/81828858-4221a680-9508-11ea-8df0-1967fa151b8e.png)

**Comment by smartinez290** [comment]
Sorry this is the error: 
![image](https://user-images.githubusercontent.com/14842422/81829215-a80e2e00-9508-11ea-9892-3ef6c1ce2405.png)

**Comment by smartinez290** [comment]
Here the XML: [Testing-Scenario-III-5ebaf1842af19b000629dad0_20200513_144818.zip](https://github.com/usnistgov/hl7-igamt/files/4622898/Testing-Scenario-III-5ebaf1842af19b000629dad0_20200513_144818.zip)

**Comment by Jungyubw** [comment]
Fixed
