### ISSUE TITLE
New V/S no redirecting 

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#922]
Created a V/S with codes/ with redirect selected. 
V/S was created but not redirected. 

![image](https://user-images.githubusercontent.com/14842422/79902505-98a33580-83df-11ea-8632-871296cf8097.png)

**Comment by smartinez290** [comment]
@Abdelghani90 is this issue going to be fixed in the next deployment?

**Comment by Abdelghani90** [comment]
I am not sure this is low priority for now.
