### ISSUE TITLE
Selection of conformance profiles while exporting to GVT does not wok

### ISSUE THREAD

**Issue by ncrouzier-nist** [usnistgov/hl7-igamt#924]
In IGAMT-2, whatever the profiles I select while exporting to GVT all of them are sent to GVT.

![image](https://user-images.githubusercontent.com/14352180/80130450-94555480-8566-11ea-98bd-e32dd6d97630.png)
Here I selected PCD01 but both PCD01 and ACK got sent to GVT

**Comment by Jungyubw** [comment]
fixed
