### ISSUE TITLE
flavor extension naming limited to 4 is too restrictive

### ISSUE THREAD

**Issue by ncrouzier-nist** [usnistgov/hl7-igamt#928]
If 4 is the recommend max length, it should only be a suggestion imho.

For example in PCD I want to name MSH flavor associated with their profiles 
MSH_PCD or MSH_PCD01  MSH_PCD12 etc

**Comment by smartinez290** [comment]
@Abdelghani90 same issue here. Immunization is using IZ_001. IGAMT does not allow me to use this extension.
