### ISSUE TITLE
Complex Conditional Predicate editing issues

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#936]
1. Created a conditional Predicate using a complex construct.
![image](https://user-images.githubusercontent.com/14842422/80618703-b9880e00-8a11-11ea-86c9-c5a88f455cee.png)

2. Try to edit to change the usage, but I am force to re-create the predicate again. Also, the construct is not the CP construct.

![image](https://user-images.githubusercontent.com/14842422/80619010-1aafe180-8a12-11ea-85b2-7f2b1bec735b.png)

**Comment by smartinez290** [comment]
@Abdelghani90 also... I tried to create the CP again from the beginning, but the  selected usage R/RE is changed to R/X.

**Comment by HossamT** [comment]
Thanks for reporting this, I am going to take care of it
