### ISSUE TITLE
MSH missing fields - HL7 2.5.1

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#943]
@Abdelghani90 @carolinerosin 
In working on 2.5.1 IG... notice that the MSH segment is missing fields. 
Here is the 2.5.1 in old IGAMT
![image](https://user-images.githubusercontent.com/14842422/81070531-584cb880-8eb1-11ea-9b96-c81f3ebf9ec6.png)
IGAMT-2 -- missing MSH-22-25
![image](https://user-images.githubusercontent.com/14842422/81070648-892ced80-8eb1-11ea-800b-d3bff2d7c707.png)

**Comment by carolinerosin** [comment]
This is weird, because MSH only has 21 fields in 2.5.1 (in the pdf from the standard), so looks like IGAMT-2 is correct, but not old igamt ?

**Comment by smartinez290** [comment]
@carolinerosin But,  the Immunization 2.5.1 IG that I am working on is calling for it:

![image](https://user-images.githubusercontent.com/14842422/81072189-c6927a80-8eb3-11ea-90ec-b2cf37e59801.png)

**Comment by carolinerosin** [comment]
I just checked in some of my 2.5.1 IGs in old IGAMT, but my MSH only has 21 fields - @smartinez290 can you double check that your MSH wit 25 fields is really a 2.5.1 (and not another version ) ?

**Comment by smartinez290** [comment]
[hl7_2_5_1_release_1_5__2018_update.pdf](https://github.com/usnistgov/hl7-igamt/files/4581065/hl7_2_5_1_release_1_5__2018_update.pdf)
This is the IG I am working from, I do not see anything there saying that the MSH is from another version.

**Comment by Abdelghani90** [comment]
I have just checked the MSH 2.5.1 in both IGAMT-2 and old IGAMT databases. they have both only 21 fields

**Comment by smartinez290** [comment]
@carolinerosin @Abdelghani90 I will take this issue back to the SMEs. Thanks.

**Comment by carolinerosin** [comment]
yep, because so far, the MSH (2.5.1) is correct in old igamt and igamt-2
This is from the base standard :
![image](https://user-images.githubusercontent.com/13591511/81074747-72899500-8eb7-11ea-888f-bff14e6ea0ab.png)

**Comment by smartinez290** [comment]
@carolinerosin Thanks. I will follow up with the SMEs.

**Comment by smartinez290** [comment]
It was pre-adopted
