### ISSUE TITLE
Adding comments to a segment field

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#944]
Tried to add a comment, but it was truncated. I guess there is a maximum number of character. 

Is it possible to make the pop-up box bigger?

![image](https://user-images.githubusercontent.com/14842422/81079097-17f33780-8ebd-11ea-96e7-9514ff6286c4.png)

**Comment by Abdelghani90** [comment]
You can use definition text if it fits your use case. but the comments are limited to avoid problems in the export display

**Comment by smartinez290** [comment]
@Abdelghani90 I see ... I will check how the Definition text is exported. The IG I am developing is using has a comment column with this text.
