### ISSUE TITLE
Can't create conditional predicate using a different context

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#945]
@Abdelghani90 @Jungyubw I am trying to create the following CP on ORC-12, but I can't select from a different context. 

If the first occurrence of RXA-9.1 is valued "00" and RXA-20 is valued "CP" or "PA"

![image](https://user-images.githubusercontent.com/14842422/81083885-23e1f800-8ec3-11ea-81a9-7c313504de19.png)

**Comment by HossamT** [comment]
This should be a message level predicate

**Comment by smartinez290** [comment]
@HossamT Thanks.
