### ISSUE TITLE
2.5.1 MSA structure - Usage

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#947]
@carolinerosin @Abdelghani90 Notice the usage and DT on MSA-5. There is an unwanted conditional predicate there.  Workin

![image](https://user-images.githubusercontent.com/14842422/81102849-374e8c80-8ede-11ea-8624-79dfe8357ec9.png)

**Comment by smartinez290** [comment]
@carolinerosin @Abdelghani90 I noticed this started to happen in other segments... so I decided to log out and, refresh and logged back in. They are now gone... something weird is going on, I had a similar situation before, but I could not recreate.

**Comment by carolinerosin** [comment]
The dataype is correct, the field is "withdrawn" (usage W) so there is no datatype.
This unwanted predicate is more concerning - probably a bug somewhere
