### ISSUE TITLE
2.5.1 QPD structure missing fields

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#948]
Old IGAMT 2.5.1 QPD Structure:
![image](https://user-images.githubusercontent.com/14842422/81105914-b645c400-8ee2-11ea-82de-2eb261e7b623.png)

IGAMT-2 
![image](https://user-images.githubusercontent.com/14842422/81105865-a0380380-8ee2-11ea-9eb9-6278f78e90b4.png)

**Comment by Abdelghani90** [comment]
<img width="1438" alt="Screen Shot 2020-05-05 at 3 21 20 PM" src="https://user-images.githubusercontent.com/16800878/81106791-2b65c900-8ee4-11ea-8918-d2b86e3793bc.png">

**Comment by Abdelghani90** [comment]
Maybe the fields were added by the users in the past. If you check the hl7 QPD you will have only 3 fields.

**Comment by smartinez290** [comment]
@Abdelghani90 I will  check on that. The 2.5.1 IG does not indicate anything...
Thanks.
