### ISSUE TITLE
Constant value not exported

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#967]
Working on a derived IG,  added a constant value to MSH-8
![image](https://user-images.githubusercontent.com/14842422/83296090-1c5df800-a1be-11ea-860d-7b2fbe4490b5.png)

The constant value is not exported -- I exported (customized, Delta On/Hide)
![image](https://user-images.githubusercontent.com/14842422/83296265-79f24480-a1be-11ea-9610-afa8398ea8cb.png)

Still there is no option to include the constant value column in the export.

**Comment by smartinez290** [comment]
@YoussefBouij was this issue supposed to be fixed in the June 10 deployment. I exported a regular IG with a constant value and it was not exported.

**Comment by YoussefBouij** [comment]
No not yet. Constant value and Definition text have yet to be exported. I only implemented Comments for now.

Regards,
Youssef

**Comment by smartinez290** [comment]
@YoussefBouij Thanks.
