### ISSUE TITLE
Editing Free-Text CS assertion

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#970]
I was able to create the free text CS with an assertion. I pushed it to GVT and it work perfectly. 
But, I had an issue in the process trying to edit an assertion. It looks like it takes the edit, but when the profile was pushed to GVT it generated an error related to the edited text. It was still recognizing the edited. I had to delete the IG and re-enter the assertion.

**Comment by Jungyubw** [comment]
@smartinez290 Can you show me this? (maybe on bluejeans) I cannot produce this.

**Comment by Jungyubw** [comment]
Fixed
